//source of inspiration NovaEngineering:World
#priority 50
#loader crafttweaker reloadable

//导包
import mods.modularmachinery.RecipePrimer;
import mods.modularmachinery.RecipeBuilder;
import crafttweaker.item.IItemStack;
import crafttweaker.data.IData;
import crafttweaker.item.IIngredient;
import crafttweaker.oredict.IOreDictEntry;
import crafttweaker.liquid.ILiquidStack;
import crafttweaker.oredict.IOreDict;

import mods.modularmachinery.IMachineController;
import mods.modularmachinery.RecipeModifierBuilder;
import mods.modularmachinery.ActiveMachineRecipe;
import mods.modularmachinery.RecipeAdapterBuilder;
import mods.modularmachinery.MachineModifier;

import mods.modularmachinery.MMEvents;
import mods.modularmachinery.MachineTickEvent;
import mods.modularmachinery.RecipeStartEvent;
import mods.modularmachinery.RecipeFinishEvent;
import mods.modularmachinery.ControllerGUIRenderEvent;

MachineModifier.setMaxThreads("assembly_line", 4);
MachineModifier.setMaxParallelism("assembly_line", 64);

MMEvents.onControllerGUIRender("assembly_line", function(event as ControllerGUIRenderEvent) {
    val controller as IMachineController = event.controller;
    event.extraInfo = "§a装配线的配方表以控制器头最近的为起始点开始计算，重复道具不可堆叠，即使重复的材料出现在不同的位置，也要严格按照合成表出现位置的顺序去标记材料进行自动化合成";
});

RecipeBuilder.newBuilder("compacted", "assembly_line", 3000)
.addEnergyPerTickInput(32768)
.addFluidInput(<liquid:creosote> * 12800).setTag("fluid_input_0")
.addFluidInput(<liquid:etchacid> * 4800).setTag("fluid_input_1")
.addFluidInput(<liquid:superheatedmoltensodium> * 2880).setTag("fluid_input_2")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 16).setTag("input_0")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 16).setTag("input_1")
.addItemInput(<calculator:atomicassembly> * 4).setTag("input_2")
.addItemInput(<calculator:atomicassembly> * 4).setTag("input_3")
.addItemInput(<pneumaticcraft:plastic:14> * 32).setTag("input_line_0")
.addItemInput(<pneumaticcraft:plastic:14> * 32).setTag("input_line_1")
.addItemInput(<pneumaticcraft:plastic> * 32).setTag("input_line_2")
.addItemInput(<pneumaticcraft:plastic> * 32).setTag("input_line_3")
.addItemInput(<pneumaticcraft:ingot_iron_compressed> * 16).setTag("input_line_4")
.addItemInput(<pneumaticcraft:ingot_iron_compressed> * 16).setTag("input_line_5")
.addItemInput(<moreplates:compressed_iron_gear> * 8).setTag("input_line_6")
.addItemInput(<moreplates:compressed_iron_plate> * 16).setTag("input_line_7")
.addItemOutput(<compactmachines3:fieldprojector> * 4).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("basic", "assembly_line", 20)
.addEnergyPerTickInput(1024)
.addFluidInput(<liquid:plastic> * 288).setTag("fluid_input_0")
.addItemInput(<enderio:item_material:20> * 4).setTag("input_0")
.addItemInput(<enderio:item_material:20> * 4).setTag("input_1")
.addItemInput(<enderio:item_alloy_ingot:4> * 2).setTag("input_2")
.addItemInput(<enderio:item_alloy_ingot:4> * 2).setTag("input_3")
.addItemInput(<moreplates:conductive_iron_plate>).setTag("input_line_0")
.addItemInput(<moreplates:conductive_iron_plate>).setTag("input_line_1")
.addItemOutput(<enderio:item_basic_capacitor>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("double", "assembly_line", 20)
.addEnergyPerTickInput(4096)
.addFluidInput(<liquid:plastic> * 288).setTag("fluid_input_0")
.addFluidInput(<liquid:nutrient_distillation> * 576).setTag("fluid_input_1")
.addItemInput(<moreplates:dark_steel_gear>).setTag("input_0")
.addItemInput(<enderio:item_basic_capacitor>).setTag("input_1")
.addItemInput(<enderio:item_basic_capacitor>).setTag("input_2")
.addItemInput(<enderio:item_basic_capacitor>).setTag("input_3")
.addItemInput(<enderio:item_basic_capacitor>).setTag("input_line_0")
.addItemInput(<enderio:item_alloy_ingot:1> * 2).setTag("input_line_1")
.addItemInput(<enderio:item_alloy_ingot:1> * 2).setTag("input_line_2")
.addItemInput(<enderio:item_alloy_ingot> * 2).setTag("input_line_3")
.addItemInput(<enderio:item_alloy_ingot> * 2).setTag("input_line_4")
.addItemInput(<immersiveintelligence:material:8> * 8).setTag("input_line_5")
.addItemInput(<immersiveintelligence:material:8> * 8).setTag("input_line_6")
.addItemOutput(<enderio:item_basic_capacitor:1> * 3).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("eight", "assembly_line", 20)
.addEnergyPerTickInput(16384)
.addFluidInput(<liquid:plastic> * 288).setTag("fluid_input_0")
.addFluidInput(<liquid:nutrient_distillation> * 576).setTag("fluid_input_1")
.addFluidInput(<liquid:ender_distillation> * 576).setTag("fluid_input_2")
.addItemInput(<moreplates:vivid_alloy_gear>).setTag("input_0")
.addItemInput(<enderio:item_basic_capacitor:1>).setTag("input_1")
.addItemInput(<enderio:item_basic_capacitor:1>).setTag("input_2")
.addItemInput(<enderio:item_basic_capacitor:1>).setTag("input_3")
.addItemInput(<enderio:item_basic_capacitor:1>).setTag("input_line_0")
.addItemInput(<enderio:item_alloy_ingot:2> * 2).setTag("input_line_1")
.addItemInput(<enderio:item_alloy_ingot:2> * 2).setTag("input_line_2")
.addItemInput(<enderio:item_alloy_ingot:8> * 2).setTag("input_line_3")
.addItemInput(<enderio:item_alloy_ingot:8> * 2).setTag("input_line_4")
.addItemInput(<immersiveintelligence:material:4> * 2).setTag("input_line_5")
.addItemInput(<immersiveintelligence:material:4> * 2).setTag("input_line_6")
.addItemOutput(<enderio:item_basic_capacitor:2> * 3).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("crystalline", "assembly_line", 20)
.addEnergyPerTickInput(32768)
.addFluidInput(<liquid:plastic> * 288).setTag("fluid_input_0")
.addFluidInput(<liquid:nutrient_distillation> * 576).setTag("fluid_input_1")
.addFluidInput(<liquid:ender_distillation> * 576).setTag("fluid_input_2")
.addFluidInput(<liquid:vapor_of_levity> * 288).setTag("fluid_input_3")
.addItemInput(<moreplates:vivid_alloy_gear>).setTag("input_0")
.addItemInput(<enderio:item_basic_capacitor:2>).setTag("input_1")
.addItemInput(<enderio:item_basic_capacitor:2>).setTag("input_2")
.addItemInput(<enderio:item_basic_capacitor:2>).setTag("input_3")
.addItemInput(<enderio:item_basic_capacitor:2>).setTag("input_line_0")
.addItemInput(<enderio:item_alloy_endergy_ingot:1> * 2).setTag("input_line_1")
.addItemInput(<enderio:item_alloy_endergy_ingot:1> * 2).setTag("input_line_2")
.addItemInput(<enderio:item_alloy_endergy_ingot:5> * 6).setTag("input_line_3")
.addItemInput(<enderio:item_alloy_endergy_ingot:5> * 6).setTag("input_line_4")
.addItemInput(<immersiveintelligence:material:9>).setTag("input_line_5")
.addItemInput(<immersiveintelligence:material:9>).setTag("input_line_6")
.addItemOutput(<enderio:item_capacitor_crystalline> * 3).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("blueprint", "assembly_line", 3000)
.addEnergyPerTickInput(32768)
.addFluidInput(<liquid:etching_acid> * 10000).setTag("fluid_input_0")
.addFluidInput(<liquid:ink> * 32000).setTag("fluid_input_1")
.addFluidInput(<liquid:hydrofluoric_acid> * 4000).setTag("fluid_input_2")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 16).setTag("input_0")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 16).setTag("input_1")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 16).setTag("input_2")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 16).setTag("input_3")
.addItemInput(<immersiveengineering:material:19> * 16).setTag("input_line_0")
.addItemInput(<immersiveengineering:material:19> * 16).setTag("input_line_1")
.addItemInput(<calculator:atomicassembly>).setTag("input_line_2")
.addItemInput(<calculator:atomicassembly>).setTag("input_line_3")
.addItemInput(<immersiveengineering:material:27> * 4).setTag("input_line_4")
.addItemInput(<immersiveengineering:material:27> * 4).setTag("input_line_5")
.addItemInput(<enderio:item_material:77> * 64).setTag("input_line_6")
.addItemInput(<enderio:item_material:77> * 64).setTag("input_line_7")
.addItemInput(<pneumaticcraft:plastic:4> *16).setTag("input_line_8")
.addItemInput(<pneumaticcraft:plastic:4> * 16).setTag("input_line_9")
.addItemInput(<pneumaticcraft:plastic:4> * 16).setTag("input_line_10")
.addItemInput(<pneumaticcraft:plastic:4> * 16).setTag("input_line_11")
.addItemOutput(<immersiveengineering:blueprint>.withTag({blueprint: "electrode"})).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_core_1", "assembly_line", 100)
.addEnergyPerTickInput(2048)
.addItemInput(<pneumaticcraft:printed_circuit_board> * 2).setTag("input_0")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 2).setTag("input_1")
.addItemInput(<calculator:advancedassembly> * 2).setTag("input_2")
.addItemInput(<calculator:advancedassembly> * 2).setTag("input_3")
.addItemInput(<appliedenergistics2:material:22> * 4).setTag("input_line_0")
.addItemInput(<appliedenergistics2:material:22> * 4).setTag("input_line_1")
.addItemInput(<appliedenergistics2:material:24> * 4).setTag("input_line_2")
.addItemInput(<appliedenergistics2:material:24> * 4).setTag("input_line_3")
.addItemInput(<appliedenergistics2:material:7> * 4).setTag("input_line_4")
.addItemInput(<appliedenergistics2:material:7> * 4).setTag("input_line_5")
.addItemOutput(<appliedenergistics2:material:43> * 4).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_core_2", "assembly_line", 100)
.addEnergyPerTickInput(2048)
.addItemInput(<pneumaticcraft:printed_circuit_board> * 2).setTag("input_0")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 2).setTag("input_1")
.addItemInput(<calculator:advancedassembly> * 2).setTag("input_2")
.addItemInput(<calculator:advancedassembly> * 2).setTag("input_3")
.addItemInput(<appliedenergistics2:material:22> * 4).setTag("input_line_0")
.addItemInput(<appliedenergistics2:material:22> * 4).setTag("input_line_1")
.addItemInput(<appliedenergistics2:material:23> * 4).setTag("input_line_2")
.addItemInput(<appliedenergistics2:material:23> * 4).setTag("input_line_3")
.addItemInput(<appliedenergistics2:material:7> * 4).setTag("input_line_4")
.addItemInput(<appliedenergistics2:material:7> * 4).setTag("input_line_5")
.addItemOutput(<appliedenergistics2:material:44> * 4).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("controller", "assembly_line", 400)
.addEnergyPerTickInput(8192)
.addItemInput(<appliedenergistics2:smooth_sky_stone_block> * 16).setTag("input_0")
.addItemInput(<appliedenergistics2:smooth_sky_stone_block> * 16).setTag("input_1")
.addItemInput(<appliedenergistics2:smooth_sky_stone_block> * 16).setTag("input_2")
.addItemInput(<appliedenergistics2:smooth_sky_stone_block> * 16).setTag("input_3")
.addItemInput(<appliedenergistics2:material:24> * 16).setTag("input_line_0")
.addItemInput(<appliedenergistics2:material:24> * 16).setTag("input_line_1")
.addItemInput(<appliedenergistics2:material:12> * 16).setTag("input_line_2")
.addItemInput(<appliedenergistics2:material:12> * 16).setTag("input_line_3")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 16).setTag("input_line_4")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 16).setTag("input_line_5")
.addItemInput(<calculator:enddiamond> * 16).setTag("input_line_6")
.addItemInput(<calculator:energymodule>).setTag("input_line_7")
.addItemOutput(<appliedenergistics2:controller>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_yuanjian_item_1", "assembly_line", 100)
.addEnergyPerTickInput(1024)
.addItemInput(<appliedenergistics2:material:22> * 4).setTag("input_0")
.addItemInput(<appliedenergistics2:material:22> * 4).setTag("input_1")
.addItemInput(<appliedenergistics2:material:23> * 4).setTag("input_2")
.addItemInput(<appliedenergistics2:material:23> * 4).setTag("input_3")
.addItemInput(<minecraft:redstone> * 16).setTag("input_line_0")
.addItemInput(<minecraft:redstone> * 16).setTag("input_line_1")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_2")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_3")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 2).setTag("input_line_4")
.addItemOutput(<appliedenergistics2:material:35>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_yuanjian_item_2", "assembly_line", 100)
.addEnergyPerTickInput(2048)
.addItemInput(<appliedenergistics2:material:22> * 8).setTag("input_0")
.addItemInput(<appliedenergistics2:material:22> * 8).setTag("input_1")
.addItemInput(<appliedenergistics2:material:23> * 8).setTag("input_2")
.addItemInput(<appliedenergistics2:material:23> * 8).setTag("input_3")
.addItemInput(<minecraft:redstone> * 16).setTag("input_line_0")
.addItemInput(<minecraft:redstone> * 16).setTag("input_line_1")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_2")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_3")
.addItemInput(<enderio:item_basic_capacitor> * 2).setTag("input_line_4")
.addItemOutput(<appliedenergistics2:material:36>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_yuanjian_item_3", "assembly_line", 100)
.addEnergyPerTickInput(4096)
.addItemInput(<appliedenergistics2:material:22> * 12).setTag("input_0")
.addItemInput(<appliedenergistics2:material:22> * 12).setTag("input_1")
.addItemInput(<appliedenergistics2:material:23> * 12).setTag("input_2")
.addItemInput(<appliedenergistics2:material:23> * 12).setTag("input_3")
.addItemInput(<minecraft:redstone> * 16).setTag("input_line_0")
.addItemInput(<minecraft:redstone> * 16).setTag("input_line_1")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_2")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_3")
.addItemInput(<enderio:item_basic_capacitor:1> * 2).setTag("input_line_4")
.addItemOutput(<appliedenergistics2:material:37>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_yuanjian_item_4", "assembly_line", 100)
.addEnergyPerTickInput(8192)
.addItemInput(<appliedenergistics2:material:22> * 16).setTag("input_0")
.addItemInput(<appliedenergistics2:material:22> * 16).setTag("input_1")
.addItemInput(<appliedenergistics2:material:23> * 16).setTag("input_2")
.addItemInput(<appliedenergistics2:material:23> * 16).setTag("input_3")
.addItemInput(<minecraft:redstone> * 16).setTag("input_line_0")
.addItemInput(<minecraft:redstone> * 16).setTag("input_line_1")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_2")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_3")
.addItemInput(<enderio:item_basic_capacitor:2> * 2).setTag("input_line_4")
.addItemOutput(<appliedenergistics2:material:38>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_yuanjian_fluid_1", "assembly_line", 100)
.addEnergyPerTickInput(1024)
.addItemInput(<appliedenergistics2:material:22> * 4).setTag("input_0")
.addItemInput(<appliedenergistics2:material:22> * 4).setTag("input_1")
.addItemInput(<appliedenergistics2:material:23> * 4).setTag("input_2")
.addItemInput(<appliedenergistics2:material:23> * 4).setTag("input_3")
.addItemInput(<minecraft:dye:4> * 16).setTag("input_line_0")
.addItemInput(<minecraft:dye:4> * 16).setTag("input_line_1")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_2")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_3")
.addItemInput(<pneumaticcraft:printed_circuit_board> * 2).setTag("input_line_4")
.addItemOutput(<appliedenergistics2:material:54>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_yuanjian_fluid_2", "assembly_line", 100)
.addEnergyPerTickInput(2048)
.addItemInput(<appliedenergistics2:material:22> * 8).setTag("input_0")
.addItemInput(<appliedenergistics2:material:22> * 8).setTag("input_1")
.addItemInput(<appliedenergistics2:material:23> * 8).setTag("input_2")
.addItemInput(<appliedenergistics2:material:23> * 8).setTag("input_3")
.addItemInput(<minecraft:dye:4> * 16).setTag("input_line_0")
.addItemInput(<minecraft:dye:4> * 16).setTag("input_line_1")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_2")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_3")
.addItemInput(<enderio:item_basic_capacitor> * 2).setTag("input_line_4")
.addItemOutput(<appliedenergistics2:material:55>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_yuanjian_fluid_3", "assembly_line", 100)
.addEnergyPerTickInput(4096)
.addItemInput(<appliedenergistics2:material:22> * 12).setTag("input_0")
.addItemInput(<appliedenergistics2:material:22> * 12).setTag("input_1")
.addItemInput(<appliedenergistics2:material:23> * 12).setTag("input_2")
.addItemInput(<appliedenergistics2:material:23> * 12).setTag("input_3")
.addItemInput(<minecraft:dye:4> * 16).setTag("input_line_0")
.addItemInput(<minecraft:dye:4> * 16).setTag("input_line_1")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_2")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_3")
.addItemInput(<enderio:item_basic_capacitor:1> * 2).setTag("input_line_4")
.addItemOutput(<appliedenergistics2:material:56>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("ae_yuanjian_fluid_4", "assembly_line", 100)
.addEnergyPerTickInput(8192)
.addItemInput(<appliedenergistics2:material:22> * 16).setTag("input_0")
.addItemInput(<appliedenergistics2:material:22> * 16).setTag("input_1")
.addItemInput(<appliedenergistics2:material:23> * 16).setTag("input_2")
.addItemInput(<appliedenergistics2:material:23> * 16).setTag("input_3")
.addItemInput(<minecraft:dye:4> * 16).setTag("input_line_0")
.addItemInput(<minecraft:dye:4> * 16).setTag("input_line_1")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_2")
.addItemInput(<appliedenergistics2:quartz_glass> * 8).setTag("input_line_3")
.addItemInput(<enderio:item_basic_capacitor:2> * 2).setTag("input_line_4")
.addItemOutput(<appliedenergistics2:material:57>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("mine_4", "assembly_line", 100)
.addEnergyPerTickInput(32768)
.addFluidInput(<liquid:vapor_of_levity> * 16000).setTag("fluid_input_0")
.addItemInput(<environmentaltech:void_ore_miner_cont_3>).setTag("input_0")
.addItemInput(<environmentaltech:laser_lens_crystal> * 16).setTag("input_1")
.addItemInput(<environmentaltech:structure_frame_4> * 8).setTag("input_2")
.addItemInput(<environmentaltech:structure_frame_4> * 8).setTag("input_3")
.addItemInput(<environmentaltech:mica> * 8).setTag("input_line_0")
.addItemInput(<environmentaltech:mica> * 8).setTag("input_line_1")
.addItemInput(<environmentaltech:pladium> * 4).setTag("input_line_2")
.addItemInput(<environmentaltech:pladium> * 4).setTag("input_line_3")
.addItemInput(<enderio:item_capacitor_crystalline> * 2).setTag("input_line_4")
.addItemInput(<enderio:item_capacitor_crystalline> * 2).setTag("input_line_5")
.addItemInput(<enderio:item_capacitor_crystalline> * 2).setTag("input_line_6")
.addItemInput(<enderio:item_capacitor_crystalline> * 2).setTag("input_line_7")
.addItemInput(<immersiveintelligence:material:12> * 4).setTag("input_line_8")
.addItemInput(<immersiveintelligence:material:7> * 4).setTag("input_line_9")
.addItemOutput(<environmentaltech:void_ore_miner_cont_4>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("solar_4", "assembly_line", 100)
.addEnergyPerTickInput(32768)
.addFluidInput(<liquid:vapor_of_levity> * 16000).setTag("fluid_input_0")
.addItemInput(<environmentaltech:solar_cont_3>).setTag("input_0")
.addItemInput(<environmentaltech:solar_cell_pladium> * 16).setTag("input_1")
.addItemInput(<environmentaltech:structure_frame_4> * 8).setTag("input_2")
.addItemInput(<environmentaltech:structure_frame_4> * 8).setTag("input_3")
.addItemInput(<environmentaltech:mica> * 8).setTag("input_line_0")
.addItemInput(<environmentaltech:mica> * 8).setTag("input_line_1")
.addItemInput(<environmentaltech:pladium> * 4).setTag("input_line_2")
.addItemInput(<environmentaltech:pladium> * 4).setTag("input_line_3")
.addItemInput(<enderio:item_capacitor_crystalline> * 2).setTag("input_line_4")
.addItemInput(<enderio:item_capacitor_crystalline> * 2).setTag("input_line_5")
.addItemInput(<enderio:item_capacitor_crystalline> * 2).setTag("input_line_6")
.addItemInput(<enderio:item_capacitor_crystalline> * 2).setTag("input_line_7")
.addItemInput(<immersiveintelligence:material:12> * 4).setTag("input_line_8")
.addItemInput(<immersiveintelligence:material:7> * 4).setTag("input_line_9")
.addItemOutput(<environmentaltech:solar_cont_4>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("construture_4", "assembly_line", 100)
.addEnergyPerTickInput(8192)
.addItemInput(<environmentaltech:structure_frame_3>).setTag("input_0")
.addItemInput(<environmentaltech:structure_frame_3>).setTag("input_1")
.addItemInput(<environmentaltech:structure_frame_3>).setTag("input_2")
.addItemInput(<environmentaltech:structure_frame_3>).setTag("input_3")
.addItemInput(<environmentaltech:mica>).setTag("input_line_0")
.addItemInput(<environmentaltech:mica>).setTag("input_line_1")
.addItemInput(<environmentaltech:mica>).setTag("input_line_2")
.addItemInput(<environmentaltech:mica>).setTag("input_line_3")
.addItemInput(<environmentaltech:pladium_crystal> * 4).setTag("input_line_4")
.addItemInput(<environmentaltech:pladium_crystal> * 4).setTag("input_line_5")
.addItemInput(<environmentaltech:pladium_crystal> * 4).setTag("input_line_6")
.addItemInput(<environmentaltech:pladium_crystal> * 4).setTag("input_line_7")
.addItemOutput(<environmentaltech:structure_frame_4> * 4).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("advanced_criticle", "assembly_line", 100)
.addEnergyPerTickInput(4096)
.addFluidInput(<liquid:tin> * 288).setTag("fluid_input_0")
.addFluidInput(<liquid:lead> * 288).setTag("fluid_input_1")
.addItemInput(<immersiveintelligence:material:2>).setTag("input_0")
.addItemInput(<immersiveintelligence:material:2>).setTag("input_1")
.addItemInput(<immersiveintelligence:material_plate> * 2).setTag("input_2")
.addItemInput(<immersiveintelligence:material_plate> * 2).setTag("input_3")
.addItemInput(<enderio:item_material:43>).setTag("input_line_0")
.addItemInput(<pneumaticcraft:plastic:2> * 4).setTag("input_line_1")
.addItemInput(<pneumaticcraft:plastic:2> * 4).setTag("input_line_2")
.addItemOutput(<immersiveintelligence:material:5>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("chuliqi", "assembly_line", 100)
.addEnergyPerTickInput(8192)
.addFluidInput(<liquid:tin> * 576).setTag("fluid_input_0")
.addFluidInput(<liquid:lead> * 576).setTag("fluid_input_1")
.addItemInput(<immersiveintelligence:material:5>).setTag("input_0")
.addItemInput(<immersiveintelligence:material:5>).setTag("input_1")
.addItemInput(<immersiveintelligence:material_plate> * 4).setTag("input_2")
.addItemInput(<immersiveintelligence:material_plate> * 4).setTag("input_3")
.addItemInput(<enderio:item_material:44>).setTag("input_line_0")
.addItemInput(<pneumaticcraft:plastic:3> * 4).setTag("input_line_1")
.addItemInput(<pneumaticcraft:plastic:3> * 4).setTag("input_line_2")
.addItemInput(<pneumaticcraft:plastic:1> * 4).setTag("input_line_3")
.addItemInput(<pneumaticcraft:plastic:1> * 4).setTag("input_line_4")
.addItemOutput(<immersiveintelligence:material:10>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("fenzi_core", "assembly_line", 200)
.addEnergyPerTickInput(32768)
.addFluidInput(<liquid:tin> * 576).setTag("fluid_input_0")
.addFluidInput(<liquid:lead> * 576).setTag("fluid_input_1")
.addItemInput(<ic2:thick_neutron_reflector> * 4).setTag("input_0")
.addItemInput(<ic2:thick_neutron_reflector> * 4).setTag("input_1")
.addItemInput(<advanced_solar_panels:crafting:6> * 16).setTag("input_2")
.addItemInput(<advanced_solar_panels:crafting:6> * 16).setTag("input_3")
.addItemInput(<immersiveintelligence:material:12> * 4).setTag("input_line_0")
.addItemInput(<immersiveintelligence:material:12> * 4).setTag("input_line_1")
.addItemInput(<contenttweaker:mobiwusi_ingot> * 16).setTag("input_line_2")
.addItemInput(<contenttweaker:mobiwusi_ingot> * 16).setTag("input_line_3")
.addItemInput(<extrautils2:decorativesolid:8> * 8).setTag("input_line_4")
.addItemInput(<extrautils2:decorativesolid:8> * 8).setTag("input_line_5")
.addItemInput(<enderio:item_material:54>).setTag("input_line_6")
.addItemInput(<enderio:item_material:54>).setTag("input_line_7")
.addItemInput(<enderio:item_material:42>).setTag("input_line_8")
.addItemInput(<enderio:item_material:42>).setTag("input_line_9")
.addItemOutput(<advanced_solar_panels:crafting:12>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("fenzi", "assembly_line", 4500)
.addEnergyPerTickInput(32768)
.addItemInput(<advanced_solar_panels:crafting:12>).setTag("input_0")
.addItemInput(<ic2:te:80> * 4).setTag("input_1")
.addItemInput(<ic2:te:80> * 4).setTag("input_2")
.addItemInput(<ic2:te:80> * 4).setTag("input_3")
.addItemInput(<ic2:resource:13> * 8).setTag("input_line_0")
.addItemInput(<ic2:resource:13> * 8).setTag("input_line_1")
.addItemInput(<ic2:resource:13> * 8).setTag("input_line_2")
.addItemInput(<ic2:resource:13> * 8).setTag("input_line_3")
.addItemInput(<immersiveintelligence:material:7> * 8).setTag("input_line_4")
.addItemInput(<immersiveintelligence:material:7> * 8).setTag("input_line_5")
.addItemInput(<enderio:item_capacitor_crystalline> * 4).setTag("input_line_6")
.addItemInput(<enderio:item_capacitor_crystalline> * 4).setTag("input_line_7")
.addItemOutput(<advanced_solar_panels:machines>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("reaction", "assembly_line", 12000)
.addEnergyPerTickInput(131072)
.addFluidInput(<liquid:ic2coolant> * 640000).setTag("fluid_input_0")
.addItemInput(<modularmachinery:blockcasing>).setTag("input_0")
.addItemInput(<ic2:resource:13> * 4).setTag("input_1")
.addItemInput(<ic2:te:22> * 4).setTag("input_2")
.addItemInput(<ic2:te:24> * 24).setTag("input_3")
.addItemInput(<ic2:resource:11> * 16).setTag("input_line_0")
.addItemInput(<ic2:resource:11> * 16).setTag("input_line_1")
.addItemInput(<ic2:resource:11> * 16).setTag("input_line_2")
.addItemInput(<ic2:resource:11> * 16).setTag("input_line_3")
.addItemInput(<ic2:nuclear:3> * 2).setTag("input_line_4")
.addItemInput(<ic2:nuclear:3> * 2).setTag("input_line_5")
.addItemInput(<ic2:nuclear:3> * 2).setTag("input_line_6")
.addItemInput(<ic2:nuclear:3> * 2).setTag("input_line_7")
.addItemInput(<advanced_solar_panels:crafting:13>).setTag("input_line_8")
.addItemOutput(<modularmachinery:reaction_factory_controller>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("huafan", "assembly_line", 3000)
.addEnergyPerTickInput(65536)
.addItemInput(<modularmachinery:blockcasing>).setTag("input_0")
.addItemInput(<ic2:nuclear:3> * 2).setTag("input_1")
.addItemInput(<ic2:nuclear:3> * 2).setTag("input_2")
.addItemInput(<ic2:nuclear:3> * 2).setTag("input_3")
.addItemInput(<fm:cesium> * 2).setTag("input_line_0")
.addItemInput(<fm:cesium> * 2).setTag("input_line_1")
.addItemInput(<ic2:crafting:4> * 4).setTag("input_line_2")
.addItemInput(<ic2:crafting:4> * 4).setTag("input_line_3")
.addItemInput(<contenttweaker:mobiwusi_ingot> * 16).setTag("input_line_4")
.addItemInput(<contenttweaker:mobiwusi_ingot> * 16).setTag("input_line_5")
.addItemInput(<advanced_solar_panels:crafting:13>).setTag("input_line_6")
.addItemOutput(<modularmachinery:fanyingfu_controller>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("gaolu", "assembly_line", 3000)
.addEnergyPerTickInput(65536)
.addItemInput(<modularmachinery:blockcasing>).setTag("input_0")
.addItemInput(<ore:plateTitanium>).setTag("input_1")
.addItemInput(<ore:plateTitanium>).setTag("input_2")
.addItemInput(<ore:plateTitanium>).setTag("input_3")
.addItemInput(<ore:plateTitanium>).setTag("input_line_0")
.addItemInput(<enderio:item_material:51> * 4).setTag("input_line_1")
.addItemInput(<enderio:item_material:51> * 4).setTag("input_line_2")
.addItemInput(<enderio:item_material:1>).setTag("input_line_3")
.addItemInput(<enderio:item_capacitor_crystalline>).setTag("input_line_4")
.addItemInput(<enderio:item_capacitor_crystalline>).setTag("input_line_5")
.addItemInput(<advanced_solar_panels:crafting:13>).setTag("input_line_6")
.addItemOutput(<modularmachinery:gaolu_controller>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("gaolu", "assembly_line", 3000)
.addEnergyPerTickInput(16384)
.addItemInput(<mets:niobium_titanium_plate> * 4).setTag("input_0")
.addItemInput(<mets:niobium_titanium_plate> * 4).setTag("input_1")
.addItemInput(<ore:circuitAdvanced>).setTag("input_2")
.addItemInput(<ore:circuitAdvanced>).setTag("input_3")
.addItemInput(<ore:plateTitanium>).setTag("input_line_0")
.addItemInput(<mets:superconducting_cable> * 4).setTag("input_line_1")
.addItemInput(<advanced_solar_panels:crafting:5>).setTag("input_line_2")
.addItemInput(<mets:superconducting_cable> * 4).setTag("input_line_3")
.addItemInput(<advanced_solar_panels:crafting:5>).setTag("input_line_4")
.addItemOutput(<mets:super_circuit> * 4).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("yayin", "assembly_line", 6000)
.addEnergyPerTickInput(65536)
.addFluidInput(<liquid:water_1> * 8000).setTag("fluid_input_0")
.addFluidInput(<liquid:water_2> * 4000).setTag("fluid_input_1")
.addFluidInput(<liquid:water_3> * 2000).setTag("fluid_input_2")
.addFluidInput(<liquid:water_4> * 1000).setTag("fluid_input_3")
.addItemInput(<modularmachinery:blockcasing>).setTag("input_0")
.addItemInput(<threng:material:4> * 32).setTag("input_1")
.addItemInput(<threng:material:14> * 16).setTag("input_2")
.addItemInput(<threng:material:6> * 64).setTag("input_3")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_0")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_1")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_2")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_3")
.addItemInput(<enderio:item_capacitor_crystalline>).setTag("input_line_4")
.addItemInput(<enderio:item_capacitor_crystalline>).setTag("input_line_5")
.addItemOutput(<modularmachinery:yayin_controller>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("jingti", "assembly_line", 6000)
.addEnergyPerTickInput(65536)
.addFluidInput(<liquid:water_1> * 8000).setTag("fluid_input_0")
.addFluidInput(<liquid:water_2> * 4000).setTag("fluid_input_1")
.addFluidInput(<liquid:water_3> * 2000).setTag("fluid_input_2")
.addFluidInput(<liquid:water_4> * 1000).setTag("fluid_input_3")
.addItemInput(<modularmachinery:blockcasing>).setTag("input_0")
.addItemInput(<threng:material:4> * 32).setTag("input_1")
.addItemInput(<threng:material:14> * 4).setTag("input_2")
.addItemInput(<threng:material:6> * 64).setTag("input_3")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_0")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_1")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_2")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_3")
.addItemInput(<enderio:item_capacitor_crystalline>).setTag("input_line_4")
.addItemInput(<enderio:item_capacitor_crystalline>).setTag("input_line_5")
.addItemOutput(<modularmachinery:jingti_factory_controller>).setTag("output_line_end")
.build();

RecipeBuilder.newBuilder("eco", "assembly_line", 6000)
.addEnergyPerTickInput(65536)
.addFluidInput(<liquid:water_2> * 8000).setTag("fluid_input_0")
.addFluidInput(<liquid:water_3> * 4000).setTag("fluid_input_1")
.addFluidInput(<liquid:water_4> * 2000).setTag("fluid_input_2")
.addFluidInput(<liquid:water_5> * 1000).setTag("fluid_input_3")
.addItemInput(<modularmachinery:blockcasing>).setTag("input_0")
.addItemInput(<threng:material:4> * 32).setTag("input_1")
.addItemInput(<threng:material:14> * 32).setTag("input_2")
.addItemInput(<threng:material:6> * 64).setTag("input_3")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_0")
.addItemInput(<appliedenergistics2:material:47> * 64).setTag("input_line_1")
.addItemInput(<enderio:item_capacitor_crystalline>).setTag("input_line_2")
.addItemInput(<enderio:item_capacitor_crystalline>).setTag("input_line_3")
.addItemInput(<threng:big_assembler:3> * 4).setTag("input_line_4")
.addItemInput(<threng:big_assembler:4> * 4).setTag("input_line_5")
.addItemInput(<appliedenergistics2:controller> * 4).setTag("input_line_6")
.addItemInput(<appliedenergistics2:controller> * 4).setTag("input_line_7")
.addItemInput(<appliedenergistics2:crafting_storage_64k> * 4).setTag("input_line_8")
.addItemInput(<appliedenergistics2:crafting_storage_64k> * 4).setTag("input_line_9")
.addItemOutput(<modularmachinery:eco_factory_controller>).setTag("output_line_end")
.build();

/*
RecipeBuilder.newBuilder("", "assembly_line", 100)
.addEnergyPerTickInput(32768)
.addFluidInput().setTag("fluid_input_0")
.addFluidInput().setTag("fluid_input_1")
.addFluidInput().setTag("fluid_input_2")
.addFluidInput().setTag("fluid_input_3")
.addItemInput().setTag("input_0")
.addItemInput().setTag("input_1")
.addItemInput().setTag("input_2")
.addItemInput().setTag("input_3")
.addItemInput().setTag("input_line_0")
.addItemInput().setTag("input_line_1")
.addItemInput().setTag("input_line_2")
.addItemInput().setTag("input_line_3")
.addItemInput().setTag("input_line_4")
.addItemInput().setTag("input_line_5")
.addItemInput().setTag("input_line_6")
.addItemInput().setTag("input_line_7")
.addItemInput().setTag("input_line_8")
.addItemInput().setTag("input_line_9")
.addItemInput().setTag("input_line_10")
.addItemInput().setTag("input_line_11")
.addItemOutput().setTag("output_line_end")
.build();
*/
