import mods.avaritia.ExtremeCrafting;

ExtremeCrafting.remove(<avaritia:ultimate_stew> * 3);
ExtremeCrafting.remove(<avaritia:cosmic_meatballs>);
ExtremeCrafting.remove(<avaritia:resource:5>);
ExtremeCrafting.remove(<avaritiatweaks:enhancement_crystal>);
ExtremeCrafting.remove(<avaritia:neutron_collector>);
ExtremeCrafting.remove(<avaritia:neutronium_compressor>);
ExtremeCrafting.remove(<eternalsingularity:eternal_singularity>);

mods.avaritia.Compressor.add("hupojin",<avaritia:singularity:12>, 100, <contenttweaker:electrum_flux>);

ExtremeCrafting.addShaped("zhongzishouji", <avaritia:neutron_collector> * 4, [[<mets:neutron_plate>, <mets:field_generator>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <mets:field_generator>, <mets:neutron_plate>], [<mets:neutron_plate>, <extendedcrafting:material:10>, <mets:field_generator>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <mets:field_generator>, <extendedcrafting:material:10>, <mets:neutron_plate>],[<mets:neutron_plate>, <contenttweaker:mobiwusi_ingot>, <bloodmagic:slate:3>, <mets:field_generator>, <randomthings:advanceditemcollector>, <mets:field_generator>, <bloodmagic:slate:3>, <contenttweaker:mobiwusi_ingot>, <mets:neutron_plate>],[<mets:neutron_plate>, <astralsorcery:itemcraftingcomponent:4>, <contenttweaker:mobiwusi_ingot>, <bloodmagic:blood_shard:1>, <refraction:laser>, <bloodmagic:blood_shard:1>, <contenttweaker:mobiwusi_ingot>, <astralsorcery:itemcraftingcomponent:4>, <mets:neutron_plate>],[<mets:neutron_plate>, <contenttweaker:mobiwusi_ingot>, <astralsorcery:itemcraftingcomponent:4>, <refraction:laser>, <enderio:item_capacitor_stellar>, <refraction:laser>, <astralsorcery:itemcraftingcomponent:4>, <contenttweaker:mobiwusi_ingot>, <mets:neutron_plate>],[<mets:neutron_plate>, <astralsorcery:itemcraftingcomponent:4>, <contenttweaker:mobiwusi_ingot>, <bloodmagic:blood_shard:1>, <refraction:laser>, <bloodmagic:blood_shard:1>, <contenttweaker:mobiwusi_ingot>, <astralsorcery:itemcraftingcomponent:4>, <mets:neutron_plate>],[<mets:neutron_plate>, <contenttweaker:mobiwusi_ingot>, <bloodmagic:slate:3>, <mets:field_generator>, <randomthings:advanceditemcollector>, <mets:field_generator>, <bloodmagic:slate:3>, <contenttweaker:mobiwusi_ingot>, <mets:neutron_plate>],[<mets:neutron_plate>, <extendedcrafting:material:10>, <mets:field_generator>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <mets:field_generator>, <extendedcrafting:material:10>, <mets:neutron_plate>],[<mets:neutron_plate>, <mets:field_generator>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <randomthings:advanceditemcollector>, <mets:field_generator>, <mets:neutron_plate>]]);
ExtremeCrafting.addShaped("zhongziyasuo", <avaritia:neutronium_compressor>, [[<advanced_solar_panels:crafting:12>, <moreplates:neutronium_plate>, <pneumaticcraft:omnidirectional_hopper>, <pneumaticcraft:omnidirectional_hopper>, <pneumaticcraft:omnidirectional_hopper>, <pneumaticcraft:omnidirectional_hopper>, <pneumaticcraft:omnidirectional_hopper>, <moreplates:neutronium_plate>, <advanced_solar_panels:crafting:12>], [<moreplates:neutronium_plate>, <mets:te:7>, <enderio:block_infinity:2>, <pneumaticcraft:omnidirectional_hopper>, <pneumaticcraft:omnidirectional_hopper>, <pneumaticcraft:omnidirectional_hopper>, <enderio:block_infinity:2>, <mets:te:7>, <moreplates:neutronium_plate>],[<moreplates:neutronium_plate>, <mets:te:7>, <enderio:block_infinity:2>, null, <pneumaticcraft:omnidirectional_hopper>, null, <enderio:block_infinity:2>, <mets:te:7>, <moreplates:neutronium_plate>],[<moreplates:neutronium_plate>, <mets:te:7>, <enderio:block_infinity:2>, null, <extendedcrafting:material:12>, null, <enderio:block_infinity:2>, <mets:te:7>, <moreplates:neutronium_plate>],[<moreplates:neutronium_gear>, <enderio:block_infinity:2>, <enderio:block_infinity:2>, <extendedcrafting:trimmed:4>, <avaritia:block_resource:0>, <extendedcrafting:trimmed:4>, <enderio:block_infinity:2>, <enderio:block_infinity:2>, <moreplates:neutronium_gear>],[<moreplates:neutronium_plate>, <mets:te:7>, <enderio:block_infinity:2>, null, <extendedcrafting:material:12>, null, <enderio:block_infinity:2>, <mets:te:7>, <moreplates:neutronium_plate>],[<moreplates:neutronium_plate>, <mets:te:7>, <enderio:block_infinity:2>, null, null, null, <enderio:block_infinity:2>, <mets:te:7>, <moreplates:neutronium_plate>],[<moreplates:neutronium_plate>, <mets:te:7>, <enderio:block_infinity:2>, null, null, null, <enderio:block_infinity:2>, <mets:te:7>, <moreplates:neutronium_plate>],[<advanced_solar_panels:crafting:12>, <moreplates:neutronium_plate>, <mets:neutron_plate>, <mets:neutron_plate>, <mets:neutron_plate>, <mets:neutron_plate>, <mets:neutron_plate>, <moreplates:neutronium_plate>, <advanced_solar_panels:crafting:12>]]);
ExtremeCrafting.addShaped("cuihuaji", <avaritia:resource:5> * 4, [[<calculator:atomicassembly>, null, null, null, <psi:psi_decorative:0>, null, null, null, <bloodmagic:item_demon_crystal:3>], [null, <forestry:crafting_material:6>, null, null, <refraction:disco_ball>, null, null, <bloodmagic:item_demon_crystal:2>, null],[null, null, <bloodmagic:slate:4>, null, <environmentaltech:ionite>, null, <bloodmagic:item_demon_crystal:1>, null, null],[null, null, null, <contenttweaker:xinghui_block:0>, <contenttweaker:mobiwusi_ingot>, <bloodmagic:item_demon_crystal:4>, null, null, null],[<psi:psi_decorative:1>, <avaritia:block_resource:2>, <advanced_solar_panels:crafting:13>, <contenttweaker:mobiwusi_ingot>, <eternalsingularity:eternal_singularity>, <contenttweaker:mobiwusi_ingot>, <psi:psi_decorative:2>, <threng:material:14>, <avaritia:block_resource:0>],[null, null, null, <avaritiatweaks:gaia_block>, <contenttweaker:mobiwusi_ingot>, <enderio:block_alloy_endergy:3>, null, null, null],[null, null, <avaritia:cosmic_meatballs>, null, <environmentaltech:mica>, null, <extendedcrafting:storage:0>, null, null],[null, <avaritia:ultimate_stew>, null, null, <thaumcraft:metal_void>, null, null, <mets:field_generator>, null],[<calculator:material:8>, null, null, null, <refraction:reflective_alloy_block>, null, null, null, <embers:wildfire_core>]]);
ExtremeCrafting.addShaped("qidian", <eternalsingularity:eternal_singularity>, [[<appliedenergistics2:material:47>, null, null, null, null, null, null, null, <avaritia:singularity:8>], [null, <avaritia:singularity:1>, null, null, null, null, null, <avaritia:singularity:11>, null],[null, null, <avaritia:singularity:2>, null, null, null, <avaritia:singularity:10>, null, null],[null, null, null, <avaritia:singularity:3>, null, <avaritia:singularity:9>, null, null, null],[null, null, null, null, <avaritia:singularity:12>, null, null, null, null],[null, null, null, <avaritia:singularity:14>, null, <avaritia:singularity:5>, null, null, null],[null, null, <avaritia:singularity:13>, null, null, null, <avaritia:singularity:6>, null, null],[null, <avaritia:singularity:0>, null, null, null, null, null, <avaritia:singularity:7>, null],[<avaritia:singularity:4>, null, null, null, null, null, null, null, <appliedenergistics2:material:47>]]);
