# VintageFix config file

mixin.allocation_rate=false
mixin.backports.new_world_name=false
mixin.backports.white_button_text=false
mixin.blockstates=false
mixin.branding=false
mixin.bugfix.entity_disappearing=false
mixin.bugfix.exit_freeze=false
mixin.bugfix.extrautils=false
mixin.bugfix.slow_tps_catchup=false
mixin.bugfix.tab_complete_ddos=false
mixin.chunk_access=false
mixin.dynamic_resources=false
mixin.dynamic_resources.background_item_bake=false
mixin.dynamic_resources.hide_model_exceptions=false
mixin.dynamic_structures=false
mixin.invisible_subchunks=false
mixin.jar_discoverer_cache=false
mixin.mod_opts.agricraft=false
mixin.model_optimizations.dedup_baked_quad=false
mixin.model_optimizations.dedup_multipart=false
mixin.model_optimizations.dedup_quad_lists=false
mixin.model_optimizations.location_canon=false
mixin.model_optimizations.simpler_perspective_wrapper=false
mixin.resourcepacks=false
mixin.textures=false
mixin.version_protest=false
