import mods.forestry.ThermionicFabricator;

ThermionicFabricator.removeCast(<forestry:flexible_casing>);
ThermionicFabricator.removeCast(<forestry:thermionic_tubes:7> * 4);

ThermionicFabricator.addCast(<forestry:flexible_casing>, [[<botania:cellblock>,<planttech2:plantium_ingot>,<botania:cellblock>],[<planttech2:plantium_ingot>,null,<planttech2:plantium_ingot>],[<botania:cellblock>,<planttech2:plantium_ingot>,<botania:cellblock>]], <liquid: glass> * 144, <forestry:impregnated_casing>);
ThermionicFabricator.addCast(<buildcraftfactory:pump>, [[<minecraft:iron_ingot>,<buildcraftfactory:tank>,<minecraft:iron_ingot>],[<magneticraft:heavy_plates:5>,<ore:gearIron>,<magneticraft:heavy_plates:5>],[<minecraft:iron_ingot>,<buildcraftfactory:tank>,<minecraft:iron_ingot>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<forestry:thermionic_tubes:7> * 4, [[null,<botania:blazeblock>,null],[<magneticraft:crafting:4>,<botania:blazeblock>,<magneticraft:crafting:4>],[<botania:blazeblock>,<botania:blazeblock>,<botania:blazeblock>]], <liquid: glass> * 144, <roots:infernal_bulb>);
ThermionicFabricator.addCast(<forestry:beehives>, [[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>],[<minecraft:hay_block>,<ore:treeSapling>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<forestry:beehives:1>, [[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>],[<minecraft:hay_block>,<botania:grassseeds>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<forestry:beehives:2>, [[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<forestry:beehives:3>, [[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:dye:3>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<forestry:beehives:4>, [[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:ender_pearl>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<forestry:beehives:5>, [[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:snow>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<forestry:beehives:6>, [[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:waterlily>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<morebees:hive>, [[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:stone>,<minecraft:hay_block>],[<minecraft:hay_block>,<minecraft:hay_block>,<minecraft:hay_block>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<immersiveengineering:stone_decoration> * 9, [[<forestry:crafting_material:6>,<ic2:resource:11>,<forestry:crafting_material:6>],[<ic2:resource:11>,<forestry:impregnated_casing>,<ic2:resource:11>],[<forestry:crafting_material:6>,<ic2:resource:11>,<forestry:crafting_material:6>]], <liquid: glass> * 144);
ThermionicFabricator.addCast(<buildcraftcore:engine:1>, [[null,<forestry:chipsets:3>.withTag({T: 3 as short}),null],[<ic2:resource:11>,<forestry:impregnated_casing>,<ic2:resource:11>],[<forestry:crafting_material:6>,<ic2:resource:11>,<forestry:crafting_material:6>]], <liquid: glass> * 144);