//This file was created via CT-GUI! Editing it is not advised!
//Don't touch me!
//#Remove
recipes.remove(<tinymobfarm:ultimate_farm>);
recipes.remove(<tinymobfarm:inferno_farm>);
recipes.remove(<draconicevolution:wyvern_energy_core>);
recipes.remove(<draconicevolution:draconic_energy_core>);
recipes.remove(<extendedcrafting:compressor>);
recipes.remove(<extendedcrafting:material:19>);
recipes.remove(<extendedcrafting:material:13>);
recipes.remove(<extendedcrafting:material:17>);
recipes.remove(<botania:alfheimportal>);
recipes.remove(<randomthings:basicredstoneinterface>);
recipes.remove(<draconicevolution:wyvern_core>);
recipes.removeShapeless(<extendedcrafting:material:36>, [<minecraft:iron_ingot>, <minecraft:ender_pearl>]);
recipes.remove(<draconicevolution:draconic_core>);
recipes.remove(<qmd:ore_leacher>);
recipes.remove(<nuclearcraft:assembler>);
recipes.remove(<nuclearcraft:solid_fission_controller>);
recipes.remove(<nuclearcraft:fission_irradiator> * 4);
recipes.remove(<nuclearcraft:part:3>);
recipes.remove(<nuclearcraft:compound:1> * 2);
recipes.remove(<deepmoblearning:data_model_chaosguardian>);
recipes.remove(<nuclearcraft:manufactory>);
recipes.remove(<nuclearcraft:part:2>);
recipes.remove(<nuclearcraft:part:1>);
recipes.remove(<nuclearcraft:part> * 2);
recipes.remove(<calculator:flawlessassembly>);
recipes.remove(<calculator:processingchamber>);
recipes.remove(<calculator:precisionchamber>);
recipes.remove(<calculator:analysingchamber>);
recipes.remove(<calculator:fabricationchamber>);
recipes.remove(<calculator:reassemblychamber>);
recipes.remove(<calculator:restorationchamber>);
recipes.remove(<calculator:extractionchamber>);
recipes.remove(<calculator:atomicmultiplier>);
recipes.remove(<deepmoblearning:polymer_clay> * 16);
recipes.remove(<deepmoblearning:data_model_error>);
recipes.remove(<deepmoblearning:data_model_gaia>);
recipes.remove(<calculator:flawlessgreenhouse>);
recipes.remove(<calculator:advancedgreenhouse>);
recipes.remove(<tp:netherstar_block>);
recipes.remove(<libvulpes:advstructuremachine> * 16);
recipes.remove(<avaritia:extreme_crafting_table>);
recipes.remove(<extendedcrafting:table_elite>);
recipes.remove(<environmentaltech:lightning_cont_1>);
recipes.remove(<environmentaltech:lightning_cont_2>);
recipes.remove(<environmentaltech:lightning_cont_3>);
recipes.remove(<environmentaltech:lightning_cont_4>);
recipes.remove(<environmentaltech:lightning_cont_5>);
recipes.remove(<environmentaltech:lightning_cont_6>);
recipes.remove(<environmentaltech:void_ore_miner_cont_6>);
recipes.remove(<environmentaltech:solar_cont_6>);
recipes.remove(<environmentaltech:solar_cont_2>);
recipes.remove(<environmentaltech:solar_cont_5>);
recipes.remove(<environmentaltech:void_ore_miner_cont_5>);
recipes.remove(<extendedcrafting:material:18>);
recipes.remove(<deepmoblearning:machine_casing>);
recipes.remove(<extendedcrafting:material:16>);
recipes.remove(<avaritia:resource>);
recipes.remove(<avaritia:resource:1>);
recipes.remove(<enderio:item_capacitor_stellar>);
recipes.remove(<enderio:item_capacitor_melodic>);
recipes.remove(<advancedrocketry:rocketmotor>);
recipes.remove(<libvulpes:structuremachine> * 16);
recipes.remove(<industrialforegoing:ore_sieve>);
recipes.remove(<industrialforegoing:mob_slaughter_factory>);
recipes.remove(<industrialforegoing:latex_processing_unit>);
recipes.remove(<industrialforegoing:tree_fluid_extractor>);
recipes.remove(<teslacorelib:machine_case>);
recipes.remove(<extrautils2:ineffableglass> * 8);
recipes.remove(<enderio:block_reinforced_obsidian>);
recipes.remove(<minecraft:end_stone>);
recipes.remove(<magneticraft:steel_gear>);
recipes.remove(<immersiveengineering:material:9>);
recipes.remove(<immersiveengineering:material:8>);
recipes.remove(<mets:super_circuit> * 2);
recipes.remove(<ore:ingotBronze> * 4);
recipes.remove(<enderio:item_capacitor_silver>);
recipes.remove(<enderio:item_capacitor_energetic_silver>);
recipes.remove(<enderio:item_capacitor_vivid>);
recipes.remove(<advanced_solar_panels:double_stone_slab>);
recipes.remove(<industrialforegoing:conveyor>);
recipes.remove(<extrautils2:compoundbow>);
recipes.remove(<extrautils2:fireaxe>);
recipes.remove(<extrautils2:lawsword>);
recipes.remove(<extendedcrafting:material:9>);
recipes.remove(<extendedcrafting:material:15>);
recipes.remove(<extendedcrafting:material>);
recipes.remove(<extendedcrafting:material:7> * 2);
recipes.remove(<industrialforegoing:laser_base>);
recipes.remove(<industrialforegoing:laser_drill>);
recipes.remove(<bloodmagic:soul_forge>);
recipes.remove(<bloodmagic:altar>);
recipes.remove(<modularmachinery:blockmepatternprovider>);
recipes.remove(<mets:te:22>);
recipes.remove(<ic2:te:63>);
recipes.remove(<ic2:te:61>);
recipes.remove(<mets:field_generator>);
recipes.remove(<mets:living_circuit>);
recipes.remove(<deepmoblearningbm:digital_agonizer>);
recipes.remove(<deepmoblearning:soot_covered_plate> * 8);
recipes.remove(<extendedcrafting:table_advanced>);
recipes.remove(<mets:tachyon_disruptor>);
recipes.remove(<mets:niobium_titanium_dust> * 2);
furnace.remove(<qmd:ingot:1>);
furnace.remove(<qmd:ingot:3>);
recipes.remove(<ic2:te:24>);
recipes.remove(<ic2:dust:11>);
recipes.remove(<essentialcraft:monsterclinger>);
recipes.remove(<essentialcraft:research_book>.withTag({tier: 0}));
recipes.remove(<mets:te:5>);
recipes.remove(<frogcraftrebirth:machine_2>);
recipes.remove(<ic2:te:50>);
recipes.remove(<mets:te:23>);
recipes.remove(<advanced_solar_panels:machines:5>);
recipes.remove(<advanced_solar_panels:machines:4>);
recipes.remove(<advanced_solar_panels:machines:2>);
recipes.remove(<enderio:item_material:67> * 4);
recipes.remove(<enderio:item_material:52> * 6);
recipes.remove(<enderio:item_material:51> * 6);
recipes.remove(<ic2:crafting:4>);
recipes.remove(<advanced_solar_panels:machines>);
recipes.remove(<advanced_solar_panels:crafting:12>);
recipes.remove(<enderio:item_material:66>);
recipes.remove(<immersiveintelligence:material_dust> * 3);
recipes.remove(<environmentaltech:structure_frame_4>);
recipes.remove(<environmentaltech:void_ore_miner_cont_4>);
recipes.remove(<environmentaltech:solar_cont_4>);
recipes.remove(<appliedenergistics2:material:57>);
recipes.remove(<appliedenergistics2:material:56>);
recipes.remove(<appliedenergistics2:material:55>);
recipes.remove(<appliedenergistics2:material:54>);
recipes.remove(<appliedenergistics2:material:38>);
recipes.remove(<appliedenergistics2:material:37>);
recipes.remove(<appliedenergistics2:material:36>);
recipes.remove(<appliedenergistics2:material:35>);
recipes.remove(<appliedenergistics2:controller>);
recipes.remove(<appliedenergistics2:material:44> * 2);
recipes.remove(<appliedenergistics2:material:43> * 2);
recipes.remove(<enderio:item_capacitor_crystalline>);
recipes.remove(<enderio:item_basic_capacitor:2>);
recipes.remove(<enderio:item_basic_capacitor:1>);
recipes.remove(<enderio:item_basic_capacitor>);
recipes.remove(<enderio:item_material>);
recipes.remove(<ae2stuff:inscriber>);
recipes.remove(<appliedenergistics2:drive>);
recipes.remove(<compactmachines3:fieldprojector> * 4);
recipes.remove(<modularmachinery:blockenergyoutputhatch:1>);
recipes.remove(<modularmachinery:blockenergyoutputhatch>);
recipes.remove(<modularmachinery:blockenergyinputhatch:1>);
recipes.remove(<modularmachinery:blockenergyinputhatch>);
recipes.remove(<modularmachinery:blockfluidoutputhatch:1>);
recipes.remove(<modularmachinery:blockfluidoutputhatch>);
recipes.remove(<modularmachinery:blockfluidinputhatch:1>);
recipes.remove(<modularmachinery:blockfluidinputhatch>);
recipes.remove(<modularmachinery:blockoutputbus:1>);
recipes.remove(<modularmachinery:blockoutputbus>);
recipes.remove(<modularmachinery:blockinputbus:1>);
recipes.remove(<modularmachinery:blockinputbus>);
recipes.remove(<modularmachinery:blockcasing:4> * 4);
recipes.remove(<extrautils2:ingredients:5> * 9);
recipes.remove(<extrautils2:ingredients:5>);
recipes.remove(<astralsorcery:blockaltar>);
recipes.remove(<aetherworks:block_aether>);
recipes.remove(<extrautils2:suncrystal:250>);
recipes.remove(<extrautils2:angelring>);
recipes.remove(<extrautils2:machine>);
recipes.remove(<extrautils2:resonator>);
recipes.remove(<modularmachinery:itemmodularium> * 5);
recipes.remove(<pneumaticcraft:printed_circuit_board>);
recipes.remove(<pneumaticcraft:amadron_tablet:30000>);
furnace.remove(<appliedenergistics2:material:5>);
recipes.remove(<randomthings:timeinabottle>);
recipes.remove(<torcherino:blocktorcherino>);
recipes.remove(<forestry:centrifuge>);
recipes.remove(<botania:pylon:1>);
recipes.remove(<minecraft:end_portal_frame>);
recipes.remove(<botanicadds:gaia_plate>);
recipes.remove(<botania:manaresource:14>);
recipes.remove(<botania:pylon:2>);
recipes.remove(<botanicadds:terra_catalyst>);
recipes.remove(<botania:storage:1>);
recipes.remove(<randomthings:ingredient:1>);
recipes.remove(<botania:livingwood:5>);
recipes.remove(<botania:terraplate>);
recipes.remove(<embers:crystal_cell>);
recipes.remove(<embers:ember_bore>);
recipes.remove(<embers:alchemy_tablet>);
recipes.remove(<embers:stamper_base>);
recipes.remove(<embers:stamper>);
recipes.remove(<embers:block_furnace>);
recipes.remove(<embers:ember_activator>);
recipes.remove(<embers:mech_core>);
recipes.remove(<ic2:resource:12>);
recipes.remove(<environmentaltech:structure_frame_3>);
recipes.remove(<environmentaltech:structure_frame_2>);
recipes.remove(<environmentaltech:void_ore_miner_cont_3>);
recipes.remove(<environmentaltech:solar_cont_3>);
recipes.remove(<calculator:atomicassembly>);
recipes.remove(<calculator:scientificcalculator>);
recipes.remove(<calculator:calculator>);
recipes.remove(<calculator:powercube>);
recipes.remove(<refraction:assembly_table>);
recipes.remove(<refraction:magnifier>);
recipes.remove(<refraction:lens> * 3);
recipes.remove(<lightningcraft:lightning_infuser>);
recipes.remove(<lightningcraft:air_terminal:6>);
recipes.remove(<lightningcraft:golf_club_gold>);
recipes.remove(<lightningcraft:stone_block> * 4);
recipes.remove(<environmentaltech:void_ore_miner_cont_2>);
recipes.remove(<immersiveintelligence:metal_decoration:4> * 3);
recipes.remove(<immersiveintelligence:metal_decoration:3> * 3);
recipes.remove(<immersiveintelligence:metal_decoration:1> * 3);
recipes.remove(<immersiveintelligence:metal_decoration:2> * 3);
recipes.remove(<ic2:crafting:2>);
recipes.remove(<ic2:crafting:1>);
recipes.remove(<immersiveengineering:metal_decoration0:5> * 2);
recipes.remove(<immersiveengineering:metal_decoration0:4> * 2);
recipes.remove(<immersiveengineering:metal_decoration0:3> * 2);
recipes.remove(<immersiveengineering:stone_decoration:1> * 3);
recipes.remove(<immersiveengineering:stone_decoration> * 3);
recipes.remove(<embers:blend_caminite> * 8);
recipes.remove(<botania:cellblock> * 3);
recipes.remove(<refraction:reflective_alloy>);
recipes.remove(<environmentaltech:litherite_crystal> * 4);
recipes.remove(<psi:programmer>);
recipes.remove(<psi:cad_assembler>);
recipes.remove(<psi:cad_assembly>);
recipes.remove(<buildcraftsilicon:assembly_table>);
recipes.remove(<buildcraftfactory:pump>);
recipes.remove(<planttech2:plantium_ingot>);
recipes.remove(<buildcraftfactory:distiller>);
recipes.remove(<buildcraftsilicon:laser>);
recipes.remove(<forestry:apiary>);
recipes.remove(<forestry:fabricator>);
recipes.remove(<forestry:squeezer>);
recipes.remove(<forestry:carpenter>);
recipes.remove(<magneticraft:crushing_table>);
recipes.remove(<fartgen:generator>);
recipes.remove(<forestry:sturdy_machine>);
recipes.remove(<buildcraftcore:engine:2>);
recipes.remove(<buildcraftcore:engine:1>);
recipes.remove(<buildcraftcore:engine>);
recipes.remove(<forestry:letters>);
recipes.remove(<forestry:engine_peat>);
recipes.remove(<forestry:engine_biogas>);
recipes.remove(<forestry:engine_clockwork>);
recipes.remove(<minecraft:cake>);
recipes.remove(<roots:fey_crafter>);
recipes.remove(<roots:grove_stone>);
recipes.remove(<roots:pyre>);
recipes.remove(<efab:base> * 4);
recipes.remove(<immersiveengineering:stone_decoration:10> * 2);
recipes.remove(<botania:blazeblock>);
recipes.remove(<efab:grid>);
recipes.remove(<minecraft:hay_block>);
recipes.remove(<minecraft:bread>);
recipes.remove(<botania:altar>);
recipes.remove(<minecraft:wheat>);
recipes.remove(<calculator:algorithmseparator>);
recipes.remove(<calculator:atomiccalculator>);
recipes.remove(<pneumaticcraft:amadron_tablet>);
//Don't touch me!
//#Add
recipes.addShaped(<additions:eq_tools-wood_scissors>, [[null, <minecraft:stick>, null],[null, <minecraft:planks>, <minecraft:stick>], [null, null, null]]);
recipes.addShapeless(<contenttweaker:wheat>, [<appliedenergistics2:creative_storage_cell>,<contenttweaker:forest_bat>,<avaritia:block_resource:1>,<avaritia:block_resource:1>,<avaritia:block_resource:1>,<avaritia:block_resource:1>,<avaritia:block_resource:1>,<avaritia:block_resource:1>,<avaritia:block_resource:1>]);
recipes.addShapeless(<botania:grassseeds>, [<botania:cellblock>]);
recipes.addShapeless(<botania:pinkinator>, [<appliedenergistics2:matter_cannon>.withTag({"@0": 4032 as long, internalMaxPower: 200000.0, ic: 4032 as long, it: 1 as short, "#0": {Craft: 0 as byte, Cnt: 4032 as long, id: "appliedenergistics2:paint_ball", Count: 1, Damage: 26 as short, Req: 0}})]);
recipes.addShaped(<minecraft:bedrock>, [[<enderio:block_infinity:2>, <enderio:block_infinity:2>, <enderio:block_infinity:2>],[<enderio:block_infinity:2>, <enderio:block_infinity:2>, <enderio:block_infinity:2>], [<enderio:block_infinity:2>, <enderio:block_infinity:2>, <enderio:block_infinity:2>]]);
recipes.addShaped(<extendedcrafting:material:36>, [[<immersiveengineering:metal:8>, <deepmoblearning:pristine_matter_enderman>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<ebwizardry:magic_crystal:1>, [[null, <essentialcraft:essence>, null],[<essentialcraft:essence>, <ebwizardry:grand_crystal>, <essentialcraft:essence>], [null, <essentialcraft:essence>, null]]);
recipes.addShaped(<deepmoblearning:data_model_chaosguardian>, [[<deepmoblearning:data_model_blank>, <draconicevolution:chaos_shard>, <draconicevolution:chaos_shard>],[<draconicevolution:chaos_shard>, <draconicevolution:chaos_shard>, <draconicadditions:chaos_heart>], [null, null, null]]);
recipes.addShaped(<contenttweaker:haipozhen_gear>, [[null, <contenttweaker:haipozhen_ingot>, null],[<contenttweaker:haipozhen_ingot>, <minecraft:iron_ingot>, <contenttweaker:haipozhen_ingot>], [null, <contenttweaker:haipozhen_ingot>, null]]);
recipes.addShaped(<qmd:ore_leacher>, [[<nuclearcraft:part:3>, <nuclearcraft:rock_crusher>, <nuclearcraft:part:3>],[<nuclearcraft:chemical_reactor>, <qmd:semiconductor:4>, <nuclearcraft:chemical_reactor>], [<nuclearcraft:part:3>, <nuclearcraft:alloy:2>, <nuclearcraft:part:3>]]);
recipes.addShaped(<nuclearcraft:assembler>, [[<nuclearcraft:part:3>, <nuclearcraft:alloy:2>, <nuclearcraft:part:3>],[<nuclearcraft:part:9>, <contenttweaker:memory_matrix>, <nuclearcraft:part:9>], [<nuclearcraft:part:3>, <nuclearcraft:part:8>, <nuclearcraft:part:3>]]);
recipes.addShaped(<nuclearcraft:solid_fission_controller>, [[<nuclearcraft:part:3>, <nuclearcraft:alloy:1>, <nuclearcraft:part:3>],[<nuclearcraft:alloy:2>, <contenttweaker:memory_matrix>, <nuclearcraft:alloy:2>], [<nuclearcraft:part:3>, <nuclearcraft:alloy:1>, <nuclearcraft:part:3>]]);
recipes.addShaped(<nuclearcraft:fission_irradiator>, [[<nuclearcraft:part:3>, <nuclearcraft:ingot:10>, <nuclearcraft:part:3>],[<nuclearcraft:alloy:12>, <contenttweaker:memory_matrix>, <nuclearcraft:alloy:12>], [<nuclearcraft:part:3>, <nuclearcraft:ingot:10>, <nuclearcraft:part:3>]]);
recipes.addShaped(<contenttweaker:cirs_black>, [[<contenttweaker:cirs_white>, <botania:dye:15>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_red>, [[<contenttweaker:cirs_white>, <botania:dye:14>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_green>, [[<contenttweaker:cirs_white>, <botania:dye:13>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_brown>, [[<contenttweaker:cirs_white>, <botania:dye:12>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_blue>, [[<contenttweaker:cirs_white>, <botania:dye:11>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_purple>, [[<contenttweaker:cirs_white>, <botania:dye:10>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_cyan>, [[<contenttweaker:cirs_white>, <botania:dye:9>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_light_gray>, [[<contenttweaker:cirs_white>, <botania:dye:8>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_gray>, [[<contenttweaker:cirs_white>, <botania:dye:7>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_pink>, [[<contenttweaker:cirs_white>, <botania:dye:6>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_lime>, [[<contenttweaker:cirs_white>, <botania:dye:5>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_yellow>, [[<contenttweaker:cirs_white>, <botania:dye:4>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_light_blue>, [[<contenttweaker:cirs_white>, <botania:dye:3>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_magenta>, [[<contenttweaker:cirs_white>, <botania:dye:2>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cirs_orange>, [[<contenttweaker:cirs_white>, <botania:dye:1>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:quyu>, [[null, null, null],[null, null, null], [<contenttweaker:num_1>, null, null]]);
recipes.addShaped(<contenttweaker:kaifang>, [[null, null, null],[null, null, <contenttweaker:num_1>], [null, null, null]]);
recipes.addShaped(<contenttweaker:chengfang>, [[null, null, null],[null, <contenttweaker:num_1>, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:chu>, [[null, null, null],[<contenttweaker:num_1>, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:cheng>, [[null, null, <contenttweaker:num_1>],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:jian>, [[null, <contenttweaker:num_1>, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<contenttweaker:jia>, [[<contenttweaker:num_1>, null, null],[null, null, null], [null, null, null]]);
recipes.addShaped(<nuclearcraft:manufactory>, [[<nuclearcraft:part>, <minecraft:redstone>, <nuclearcraft:part>],[<moreplates:infinity_plate>, <minecraft:piston>, <moreplates:infinity_plate>], [<nuclearcraft:part>, <nuclearcraft:part:4>, <nuclearcraft:part>]]);
recipes.addShaped(<deepmoblearning:polymer_clay> * 32, [[<pneumaticcraft:plastic:6>, <pneumaticcraft:ingot_iron_compressed>, <pneumaticcraft:plastic:12>],[<pneumaticcraft:ingot_iron_compressed>, <extrautils2:decorativesolid:3>, <pneumaticcraft:ingot_iron_compressed>], [<pneumaticcraft:plastic:12>, <pneumaticcraft:ingot_iron_compressed>, <pneumaticcraft:plastic:6>]]);
recipes.addShapeless(<deepmoblearning:glitch_fragment> * 3, [<deepmoblearning:glitch_heart>]);
recipes.addShapeless(<botania:floatingspecialflower>.withTag({type: "irisotos"}), [<botania:specialflower>.withTag({type: "irisotos"}),<botania:miniisland:*>]);
recipes.addShaped(<equation:fluid_tranfer>, [[null, <minecraft:bucket>, null],[<ore:gearDiamond>, <extrautils2:machine>, <ore:gearDiamond>], [<minecraft:glass>, <immersiveengineering:material:27>, <minecraft:glass>]]);
recipes.addShapeless(<equation:mana_to_fluid_1>, [<botania:manaresource:4>,<botania:livingrock>,<botania:manaresource:4>,<botania:livingrock>,<botania:manatablet>,<botania:livingrock>,<botania:manaresource:4>,<botania:livingrock>,<botania:manaresource:4>]);
recipes.addShapeless(<equation:mana_to_fluid_1>, [<equation:mana_to_fluid_2>]);
recipes.addShapeless(<equation:mana_to_fluid_2>, [<equation:mana_to_fluid_1>]);
recipes.addShapeless(<contenttweaker:ingot_electrum_flux>, [<contenttweaker:nugget_electrum_flux>,<contenttweaker:nugget_electrum_flux>,<contenttweaker:nugget_electrum_flux>,<contenttweaker:nugget_electrum_flux>,<contenttweaker:nugget_electrum_flux>,<contenttweaker:nugget_electrum_flux>,<contenttweaker:nugget_electrum_flux>,<contenttweaker:nugget_electrum_flux>,<contenttweaker:nugget_electrum_flux>]);
recipes.addShapeless(<contenttweaker:nugget_electrum_flux> * 9, [<contenttweaker:ingot_electrum_flux>]);
recipes.addShapeless(<contenttweaker:electrum_flux>, [<contenttweaker:ingot_electrum_flux>,<contenttweaker:ingot_electrum_flux>,<contenttweaker:ingot_electrum_flux>,<contenttweaker:ingot_electrum_flux>,<contenttweaker:ingot_electrum_flux>,<contenttweaker:ingot_electrum_flux>,<contenttweaker:ingot_electrum_flux>,<contenttweaker:ingot_electrum_flux>,<contenttweaker:ingot_electrum_flux>]);
recipes.addShapeless(<contenttweaker:ingot_electrum_flux> * 9, [<contenttweaker:electrum_flux>]);
recipes.addShaped(<calculator:flawlessgreenhouse>, [[<calculator:flawlessglass>, <calculator:flawlessglass>, <calculator:flawlessglass>],[<calculator:locatormodule>, <calculator:advancedgreenhouse>, <calculator:locatormodule>], [<calculator:flawlessglass>, <calculator:flawlessglass>, <calculator:flawlessglass>]]);
recipes.addShaped(<calculator:advancedgreenhouse>, [[<calculator:material:8>, <calculator:largetanzanite>, <calculator:material:8>],[<calculator:largetanzanite>, <calculator:basicgreenhouse>, <calculator:largetanzanite>], [<calculator:material:8>, <calculator:largetanzanite>, <calculator:material:8>]]);
recipes.addShaped(<libvulpes:advstructuremachine>, [[null, <libvulpes:productsheet:7>, null],[<libvulpes:productsheet:7>, <libvulpes:structuremachine>, <libvulpes:productsheet:7>], [null, <libvulpes:productsheet:7>, null]]);
recipes.addShaped(<maplesyrup:maple_sapling>, [[<forestry:royal_jelly>, <minecraft:sugar>, <forestry:royal_jelly>],[<minecraft:sugar>, <minecraft:sapling>, <minecraft:sugar>], [<forestry:royal_jelly>, <minecraft:sugar>, <forestry:royal_jelly>]]);
recipes.addShaped(<deepmoblearning:machine_casing>, [[<deepmoblearning:soot_covered_plate>, <extrautils2:decorativesolid:3>, <deepmoblearning:soot_covered_plate>],[<extrautils2:decorativesolid:3>, <deepmoblearning:soot_covered_redstone>, <extrautils2:decorativesolid:3>], [<deepmoblearning:soot_covered_plate>, <extrautils2:decorativesolid:3>, <deepmoblearning:soot_covered_plate>]]);
recipes.addShaped(<avaritia:resource>, [[<calculator:enddiamond>, null, <calculator:enddiamond>],[null, <minecraft:nether_star>, null], [<calculator:enddiamond>, null, <calculator:enddiamond>]]);
recipes.addShaped(<avaritia:resource:1>, [[null, null, null],[<avaritia:resource>, <enderio:item_alloy_endergy_ingot:2>, <avaritia:resource>], [<avaritia:resource>, <enderio:item_alloy_endergy_ingot:2>, <avaritia:resource>]]);
recipes.addShaped(<advancedrocketry:rocketmotor>, [[<mets:neutron_plate>, <mets:neutron_plate>, <mets:neutron_plate>],[<industrialforegoing:plastic>, <libvulpes:productsheet:7>, <industrialforegoing:plastic>], [<libvulpes:productsheet:7>, <botania:turntable>, <libvulpes:productsheet:7>]]);
recipes.addShaped(<industrialforegoing:ore_sieve>, [[<embers:wildfire_core>, <industrialforegoing:pink_slime>, <embers:wildfire_core>],[<thaumcraft:centrifuge>, <mets:field_generator>, <thaumcraft:centrifuge>], [<embers:wildfire_core>, <teslacorelib:machine_case>, <embers:wildfire_core>]]);
recipes.addShaped(<industrialforegoing:mob_slaughter_factory>, [[<industrialforegoing:plastic>, <deepmoblearning:glitch_infused_sword>, <industrialforegoing:plastic>],[<thaumcraft:elemental_sword>, <teslacorelib:machine_case>, <roots:living_sword>], [<industrialforegoing:plastic>, <calculator:endforgedsword>, <industrialforegoing:plastic>]]);
recipes.addShaped(<industrialforegoing:latex_processing_unit>, [[<contenttweaker:mobiwusi_ingot>, <immersiveintelligence:motor_gear:2>, <contenttweaker:mobiwusi_ingot>],[<contenttweaker:mobiwusi_ingot>, <teslacorelib:machine_case>, <contenttweaker:mobiwusi_ingot>], [<advanced_solar_panels:crafting:9>, <enderio:item_capacitor_crystalline>, <advanced_solar_panels:crafting:9>]]);
recipes.addShaped(<industrialforegoing:tree_fluid_extractor>, [[<mets:neutron_plate>, <ic2:treetap>, <mets:neutron_plate>],[<mets:neutron_plate>, <teslacorelib:machine_case>, <mets:neutron_plate>], [<mets:neutron_plate>, <ic2:treetap>, <mets:neutron_plate>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch>, [[null, null, null],[null, <minecraft:iron_block>, null], [null, <efab:rfstorage>, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch>, [[null, <efab:rfstorage>, null],[null, <minecraft:iron_block>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus>, [[null, null, null],[null, <minecraft:iron_block>, null], [null, <minecraft:chest>, null]]);
recipes.addShaped(<modularmachinery:blockinputbus>, [[null, <minecraft:chest>, null],[null, <minecraft:iron_block>, null], [null, null, null]]);
recipes.addShaped(<gugu-utils:sparkmanahatch>, [[<botania:livingrock>, <botania:pool>, <botania:livingrock>],[<botania:pool>, null, <botania:pool>], [<botania:livingrock>, <botania:pool>, <botania:livingrock>]]);
recipes.addShaped(<extrautils2:ineffableglass> * 8, [[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>],[<minecraft:glass>, <roots:moonglow_leaf>, <minecraft:glass>], [<minecraft:glass>, <minecraft:glass>, <minecraft:glass>]]);
recipes.addShaped(<enderio:block_reinforced_obsidian>, [[<enderio:item_material:20>, <minecraft:iron_bars>, <enderio:item_material:20>],[<minecraft:iron_bars>, <minecraft:obsidian>, <minecraft:iron_bars>], [<enderio:item_material:20>, <minecraft:iron_bars>, <enderio:item_material:20>]]);
recipes.addShaped(<additions:eq_tools-advanced_tool>, [[null, null, null],[null, null, <minecraft:stick>], [null, <minecraft:stick>, null]]);
recipes.addShaped(<avaritiaddons:infinity_glass> * 8, [[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>],[<minecraft:glass>, <avaritia:resource:6>, <minecraft:glass>], [<minecraft:glass>, <minecraft:glass>, <minecraft:glass>]]);
recipes.addShaped(<magneticraft:steel_gear>, [[null, <ore:ingotSteel>, null],[<ore:ingotSteel>, <magneticraft:light_plates:6>, <ore:ingotSteel>], [null, <ore:ingotSteel>, null]]);
recipes.addShaped(<ic2:fence> * 3, [[null, null, null],[<minecraft:iron_ingot>, <ore:stickIron>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <ore:stickIron>, <minecraft:iron_ingot>]]);
recipes.addShaped(<gugu-utils:environmenthatch>, [[<modularmachinery:blockcasing>, <minecraft:daylight_detector>, <modularmachinery:blockcasing>],[<projectred-integration:gate:16>, <opencomputers:motionsensor>, <rftools:sensor_block>], [<modularmachinery:blockcasing>, <calculator:rainsensor>, <modularmachinery:blockcasing>]]);
recipes.addShaped(<extrautils2:compoundbow>, [[null, <extrautils2:unstableingots>, <refraction:optic_fiber>],[<extrautils2:unstableingots>, null, <refraction:optic_fiber>], [null, <extrautils2:unstableingots>, <refraction:optic_fiber>]]);
recipes.addShaped(<extrautils2:fireaxe>, [[null, <extrautils2:unstableingots>, <extrautils2:unstableingots>],[null, <minecraft:obsidian>, <extrautils2:unstableingots>], [null, <minecraft:obsidian>, null]]);
recipes.addShaped(<extrautils2:lawsword>, [[null, <extrautils2:unstableingots>, null],[null, <extrautils2:unstableingots>, null], [null, <minecraft:obsidian>, null]]);
recipes.addShaped(<bloodmagic:soul_forge>, [[<astralsorcery:blockblackmarble:2>, null, <astralsorcery:blockblackmarble:2>],[<astralsorcery:blockblackmarble>, <bloodmagic:blood_rune>, <astralsorcery:blockblackmarble>], [<astralsorcery:blockblackmarble:2>, <astralsorcery:itemcraftingcomponent:1>, <astralsorcery:blockblackmarble:2>]]);
recipes.addShaped(<bloodmagic:altar>, [[null, <essentialcraft:mrumatrixprojection:1>, null],[<essentialcraft:genitem:35>, <essentialcraft:genitem:36>, <essentialcraft:genitem:35>], [<essentialcraft:genitem:35>, <essentialcraft:genitem:37>, <essentialcraft:genitem:35>]]);
recipes.addShaped(<mets:field_generator>, [[<mets:superconducting_cable>, <mets:living_circuit>, <mets:superconducting_cable>],[<mets:living_circuit>, <fm:cesium>, <mets:living_circuit>], [<mets:superconducting_cable>, <mets:living_circuit>, <mets:superconducting_cable>]]);
recipes.addShaped(<mets:living_circuit>, [[<mets:superconducting_cable>, <ic2:nuclear:3>, <mets:superconducting_cable>],[<mets:nano_living_metal>, <mets:super_circuit>, <mets:nano_living_metal>], [<mets:superconducting_cable>, <mets:super_iridium_compress_plate>, <mets:superconducting_cable>]]);
recipes.addShaped(<mets:tachyon_disruptor>, [[<mets:neutron_plate>, <mets:nano_living_metal>, <mets:super_lapotron_crystal>],[<mets:field_generator>, <mets:field_generator>, <mets:living_circuit>], [<mets:neutron_plate>, <mets:nano_living_metal>, <avaritia:block_resource:1>]]);
recipes.addShapeless(<mets:niobium_titanium_dust> * 2, [<ore:dustTitanium>,<ore:dustTitanium>,<ore:dustTitanium>,<ore:dustNiobium>]);
recipes.addShaped(<ic2:te:24> * 3, [[<ic2:plate:14>, <ic2:resource:13>, <ic2:plate:14>],[<ic2:resource:13>, <immersiveintelligence:material:7>, <ic2:resource:13>], [<ic2:plate:14>, <ic2:resource:13>, <ic2:plate:14>]]);
recipes.addShapeless(<essentialcraft:genitem:51>, [<environmentaltech:litherite_crystal>]);
recipes.addShapeless(<ic2:crafting:1>, [<immersiveengineering:material:27>]);
recipes.addShapeless(<ic2:crafting:2>, [<immersiveintelligence:material:7>]);
recipes.addShaped(<advanced_solar_panels:machines:5> * 4, [[<advanced_solar_panels:machines:4>, <advanced_solar_panels:machines:4>, <advanced_solar_panels:machines:4>],[<advanced_solar_panels:machines:4>, <advanced_solar_panels:crafting:13>, <advanced_solar_panels:machines:4>], [<advanced_solar_panels:machines:4>, <advanced_solar_panels:machines:4>, <advanced_solar_panels:machines:4>]]);
recipes.addShaped(<advanced_solar_panels:machines:4> * 2, [[<advanced_solar_panels:machines:3>, <advanced_solar_panels:machines:3>, <advanced_solar_panels:machines:3>],[<advanced_solar_panels:machines:3>, <immersiveintelligence:material:12>, <advanced_solar_panels:machines:3>], [<advanced_solar_panels:machines:3>, <advanced_solar_panels:machines:3>, <advanced_solar_panels:machines:3>]]);
recipes.addShaped(<advanced_solar_panels:machines:3>, [[<ic2:crafting:15>, <minecraft:lapis_block>, <ic2:crafting:15>],[<ic2:crafting:4>, <advanced_solar_panels:machines:2>, <ic2:crafting:4>], [<immersiveintelligence:material:7>, <advanced_solar_panels:crafting:4>, <immersiveintelligence:material:7>]]);
recipes.addShaped(<advanced_solar_panels:machines:2>, [[<advanced_solar_panels:crafting:6>, <advanced_solar_panels:crafting:6>, <advanced_solar_panels:crafting:6>],[<ic2:crafting:3>, <ic2:te:8>, <ic2:crafting:3>], [<immersiveintelligence:material:7>, <advanced_solar_panels:crafting:9>, <immersiveintelligence:material:7>]]);
furnace.addRecipe(<appliedenergistics2:material:5> * 8, <immersiveintelligence:material_boule>, 0.0);
recipes.addShaped(<gugu-utils:starlightinputhatch:2>, [[null, <packagedastral:constellation_focus>, null],[<packagedastral:constellation_focus>, <gugu-utils:starlightinputhatch:1>, <packagedastral:constellation_focus>], [null, <packagedastral:constellation_focus>, null]]);
recipes.addShaped(<gugu-utils:starlightinputhatch:1>, [[null, <astralsorcery:blockaltar:2>, null],[<astralsorcery:blockaltar:2>, <gugu-utils:starlightinputhatch>, <astralsorcery:blockaltar:2>], [null, <astralsorcery:blockaltar:2>, null]]);
recipes.addShaped(<gugu-utils:starlightinputhatch>, [[<astralsorcery:itemcraftingcomponent:1>, <astralsorcery:itemcraftingcomponent:1>, <astralsorcery:itemcraftingcomponent:1>],[<astralsorcery:itemcraftingcomponent:1>, <modularmachinery:blockcasing>, <astralsorcery:itemcraftingcomponent:1>], [<astralsorcery:itemcraftingcomponent:1>, <astralsorcery:itemcraftingcomponent:1>, <astralsorcery:itemcraftingcomponent:1>]]);
recipes.addShaped(<modularmachinery:blockmepatternprovider>, [[null, <ae2fc:dual_interface>, null],[<ae2fc:dual_interface>, <modularmachinery:blockcasing>, <ae2fc:dual_interface>], [null, <ae2fc:dual_interface>, null]]);
recipes.addShaped(<modularmachinery:blockmefluidoutputbus>, [[null, <appliedenergistics2:part:441>, null],[<appliedenergistics2:part:441>, <modularmachinery:blockcasing>, <appliedenergistics2:part:441>], [null, <appliedenergistics2:part:441>, null]]);
recipes.addShaped(<modularmachinery:blockmefluidinputbus>, [[null, <appliedenergistics2:fluid_interface>, null],[<appliedenergistics2:fluid_interface>, <modularmachinery:blockcasing>, <appliedenergistics2:fluid_interface>], [null, <appliedenergistics2:fluid_interface>, null]]);
recipes.addShaped(<modularmachinery:blockmeiteminputbus>, [[null, <appliedenergistics2:part:440>, null],[<appliedenergistics2:part:440>, <modularmachinery:blockcasing>, <appliedenergistics2:part:440>], [null, <appliedenergistics2:part:440>, null]]);
recipes.addShaped(<modularmachinery:blockmeitemoutputbus>, [[null, <appliedenergistics2:interface>, null],[<appliedenergistics2:interface>, <modularmachinery:blockcasing>, <appliedenergistics2:interface>], [null, <appliedenergistics2:interface>, null]]);
recipes.addShaped(<modularmachinery:blockparallelcontroller:2>, [[<mets:field_generator>, <enderio:item_capacitor_stellar>, <mets:field_generator>],[<enderio:item_capacitor_stellar>, <modularmachinery:blockparallelcontroller:1>, <enderio:item_capacitor_stellar>], [<mets:field_generator>, <enderio:item_capacitor_stellar>, <mets:field_generator>]]);
recipes.addShaped(<modularmachinery:blockparallelcontroller:3>, [[<avaritiatweaks:enhancement_crystal>, <avaritiaio:infinitecapacitor>, <avaritiatweaks:enhancement_crystal>],[<avaritiaio:infinitecapacitor>, <modularmachinery:blockparallelcontroller:2>, <avaritiaio:infinitecapacitor>], [<avaritiatweaks:enhancement_crystal>, <avaritiaio:infinitecapacitor>, <avaritiatweaks:enhancement_crystal>]]);
recipes.addShaped(<modularmachinery:blockparallelcontroller:4>, [[<extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>],[<extendedcrafting:material:32>, <modularmachinery:blockparallelcontroller:3>, <extendedcrafting:material:32>], [<extendedcrafting:singularity_ultimate>, <extendedcrafting:material:32>, <extendedcrafting:singularity_ultimate>]]);
recipes.addShaped(<modularmachinery:blockparallelcontroller:1>, [[<contenttweaker:mobiwusi_ingot>, <ic2:crafting:4>, <contenttweaker:mobiwusi_ingot>],[<ic2:crafting:4>, <modularmachinery:blockparallelcontroller>, <ic2:crafting:4>], [<contenttweaker:mobiwusi_ingot>, <ic2:crafting:4>, <contenttweaker:mobiwusi_ingot>]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:7>, [[null, null, null],[null, <modularmachinery:blockenergyoutputhatch:6>, null], [null, <efab:rfstorage_advanced>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:6>, [[null, null, null],[null, <modularmachinery:blockenergyoutputhatch:5>, null], [null, <efab:rfstorage_advanced>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:5>, [[null, null, null],[null, <modularmachinery:blockenergyoutputhatch:4>, null], [null, <efab:rfstorage_advanced>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:4>, [[null, null, null],[null, <modularmachinery:blockenergyoutputhatch:3>, null], [null, <efab:rfstorage_advanced>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:3>, [[null, null, null],[null, <modularmachinery:blockenergyoutputhatch:2>, null], [null, <efab:rfstorage_advanced>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:2>, [[null, null, null],[null, <modularmachinery:blockenergyoutputhatch:1>, null], [null, <efab:rfstorage_advanced>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch:1>, [[null, null, null],[null, <modularmachinery:blockenergyoutputhatch>, null], [null, <efab:rfstorage_advanced>, null]]);
recipes.addShaped(<modularmachinery:blockenergyoutputhatch>, [[null, null, null],[null, <modularmachinery:blockcasing>, null], [null, <efab:rfstorage_advanced>, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:7>, [[null, <efab:rfstorage_advanced>, null],[null, <modularmachinery:blockenergyinputhatch:6>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:6>, [[null, <efab:rfstorage_advanced>, null],[null, <modularmachinery:blockenergyinputhatch:5>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:5>, [[null, <efab:rfstorage_advanced>, null],[null, <modularmachinery:blockenergyinputhatch:4>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:4>, [[null, <efab:rfstorage_advanced>, null],[null, <modularmachinery:blockenergyinputhatch:3>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:3>, [[null, <efab:rfstorage_advanced>, null],[null, <modularmachinery:blockenergyinputhatch:2>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:2>, [[null, <efab:rfstorage_advanced>, null],[null, <modularmachinery:blockenergyinputhatch:1>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch:1>, [[null, <efab:rfstorage_advanced>, null],[null, <modularmachinery:blockenergyinputhatch>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockenergyinputhatch>, [[null, <efab:rfstorage_advanced>, null],[null, <modularmachinery:blockcasing>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:7>, [[null, null, null],[null, <modularmachinery:blockfluidoutputhatch:6>, null], [null, <efab:tank2>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:6>, [[null, null, null],[null, <modularmachinery:blockfluidoutputhatch:5>, null], [null, <efab:tank2>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:5>, [[null, null, null],[null, <modularmachinery:blockfluidoutputhatch:4>, null], [null, <efab:tank2>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:4>, [[null, null, null],[null, <modularmachinery:blockfluidoutputhatch:3>, null], [null, <efab:tank2>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:3>, [[null, null, null],[null, <modularmachinery:blockfluidoutputhatch:2>, null], [null, <efab:tank2>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:2>, [[null, null, null],[null, <modularmachinery:blockfluidoutputhatch:1>, null], [null, <efab:tank2>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch:1>, [[null, null, null],[null, <modularmachinery:blockfluidoutputhatch>, null], [null, <efab:tank2>, null]]);
recipes.addShaped(<modularmachinery:blockfluidoutputhatch>, [[null, null, null],[null, <modularmachinery:blockcasing>, null], [null, <efab:tank2>, null]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:7>, [[null, <efab:tank2>, null],[null, <modularmachinery:blockfluidinputhatch:6>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:6>, [[null, <efab:tank2>, null],[null, <modularmachinery:blockfluidinputhatch:5>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:5>, [[null, <efab:tank2>, null],[null, <modularmachinery:blockfluidinputhatch:4>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:4>, [[null, <efab:tank2>, null],[null, <modularmachinery:blockfluidinputhatch:3>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:3>, [[null, <efab:tank2>, null],[null, <modularmachinery:blockfluidinputhatch:2>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:2>, [[null, <efab:tank2>, null],[null, <modularmachinery:blockfluidinputhatch:1>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch:1>, [[null, <efab:tank2>, null],[null, <modularmachinery:blockfluidinputhatch>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockfluidinputhatch>, [[null, <efab:tank2>, null],[null, <modularmachinery:blockcasing>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:6>, [[null, null, null],[null, <modularmachinery:blockoutputbus:5>, null], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:5>, [[null, null, null],[null, <modularmachinery:blockoutputbus:4>, null], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:4>, [[null, null, null],[null, <modularmachinery:blockoutputbus:3>, null], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:3>, [[null, null, null],[null, <modularmachinery:blockoutputbus:2>, null], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:2>, [[null, null, null],[null, <modularmachinery:blockoutputbus:1>, null], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus:1>, [[null, null, null],[null, <modularmachinery:blockoutputbus>, null], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockoutputbus>, [[null, null, null],[null, <modularmachinery:blockcasing>, null], [null, <minecraft:hopper>, null]]);
recipes.addShaped(<modularmachinery:blockcasing:3>, [[null, <moreplates:compressed_iron_gear>, null],[<moreplates:compressed_iron_gear>, <modularmachinery:blockcasing>, <moreplates:compressed_iron_gear>], [null, <moreplates:compressed_iron_gear>, null]]);
recipes.addShaped(<modularmachinery:blockcasing:2>, [[<ic2:containment_plating>, <ic2:containment_plating>, <ic2:containment_plating>],[<ic2:containment_plating>, <modularmachinery:blockcasing>, <ic2:containment_plating>], [<ic2:containment_plating>, <ic2:containment_plating>, <ic2:containment_plating>]]);
recipes.addShaped(<modularmachinery:blockcasing:1>, [[<minecraft:iron_bars>, <minecraft:iron_bars>, <minecraft:iron_bars>],[<minecraft:iron_bars>, <modularmachinery:blockcasing>, <minecraft:iron_bars>], [<minecraft:iron_bars>, <minecraft:iron_bars>, <minecraft:iron_bars>]]);
recipes.addShaped(<modularmachinery:blockcasing:5>, [[<immersiveengineering:material:27>, <immersiveengineering:material:27>, <immersiveengineering:material:27>],[<immersiveengineering:material:27>, <modularmachinery:blockcasing>, <immersiveengineering:material:27>], [<immersiveengineering:material:27>, <immersiveengineering:material:27>, <immersiveengineering:material:27>]]);
recipes.addShaped(<modularmachinery:blockinputbus:6>, [[null, <minecraft:chest>, null],[null, <modularmachinery:blockinputbus:5>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockinputbus:5>, [[null, <minecraft:chest>, null],[null, <modularmachinery:blockinputbus:4>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockinputbus:4>, [[null, <minecraft:chest>, null],[null, <modularmachinery:blockinputbus:3>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockinputbus:3>, [[null, <minecraft:chest>, null],[null, <modularmachinery:blockinputbus:2>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockinputbus:2>, [[null, <minecraft:chest>, null],[null, <modularmachinery:blockinputbus:1>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockinputbus:1>, [[null, <minecraft:chest>, null],[null, <modularmachinery:blockinputbus>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockinputbus>, [[null, <minecraft:chest>, null],[null, <modularmachinery:blockcasing>, null], [null, null, null]]);
recipes.addShaped(<modularmachinery:blockupgradebus>, [[null, <calculator:electricdiamond>, null],[<calculator:electricdiamond>, <modularmachinery:blockcasing>, <calculator:electricdiamond>], [null, <calculator:electricdiamond>, null]]);
recipes.addShaped(<modularmachinery:blockparallelcontroller>, [[<calculator:atomicassembly>, <immersiveengineering:material:27>, <calculator:atomicassembly>],[<immersiveengineering:material:27>, <modularmachinery:blockcasing>, <immersiveengineering:material:27>], [<calculator:atomicassembly>, <immersiveengineering:material:27>, <calculator:atomicassembly>]]);
recipes.addShaped(<modularmachinery:blockcasing:4> * 2, [[<extrautils2:decorativesolid:3>, <modularmachinery:blockcasing>, <extrautils2:decorativesolid:3>],[<modularmachinery:blockcasing>, null, <modularmachinery:blockcasing>], [<extrautils2:decorativesolid:3>, <modularmachinery:blockcasing>, <extrautils2:decorativesolid:3>]]);
recipes.addShaped(<extrautils2:ingredients:5>, [[<extrautils2:ingredients:3>, <extrautils2:ingredients:3>, <extrautils2:ingredients:3>],[<extrautils2:ingredients:3>, <contenttweaker:mobiwusi_ingot>, <extrautils2:ingredients:3>], [<extrautils2:ingredients:3>, <extrautils2:ingredients:3>, <extrautils2:ingredients:3>]]);
recipes.addShapeless(<astralsorcery:itemcraftingcomponent:1> * 9, [<contenttweaker:xinghui_block>]);
recipes.addShaped(<extrautils2:angelring>, [[<extrautils2:decorativesolid:8>, <minecraft:gold_ingot>, <extrautils2:decorativesolid:8>],[<minecraft:gold_ingot>, <extrautils2:chickenring:1>, <minecraft:gold_ingot>], [<extrautils2:goldenlasso>, <minecraft:gold_ingot>, <extrautils2:goldenlasso:1>]]);
recipes.addShapeless(<botania:manaresource:14> * 9, [<avaritiatweaks:gaia_block>]);
recipes.addShaped(<contenttweaker:life_core>, [[<embers:eldritch_insignia>, <embers:flame_barrier>, <embers:intelligent_apparatus>],[<embers:ancient_motive_core>, <embers:wildfire_core>, <embers:ancient_motive_core>], [<embers:shifting_scales>, <embers:focal_lens>, <embers:shifting_scales>]]);
recipes.addShaped(<embers:alchemy_tablet>, [[<embers:block_dawnstone>, <embers:block_dawnstone>, <embers:block_dawnstone>],[<embers:stairs_caminite_brick>, <embers:plate_dawnstone>, <embers:stairs_caminite_brick>], [<embers:plate_dawnstone>, <embers:block_caminite_brick>, <embers:plate_dawnstone>]]);
recipes.addShaped(<embers:beam_cannon>, [[<immersiveengineering:metal:38>, <embers:ember_cluster>, <immersiveengineering:metal:38>],[<immersiveengineering:metal:38>, <embers:ember_cluster>, <immersiveengineering:metal:38>], [<embers:block_caminite_brick>, <embers:block_caminite_brick>, <embers:block_caminite_brick>]]);
recipes.addShaped(<embers:stamper_base>, [[null, null, null],[<embers:block_caminite_brick>, <minecraft:hopper>, <embers:block_caminite_brick>], [<moreplates:manasteel_plate>, <embers:item_pipe>, <moreplates:manasteel_plate>]]);
recipes.addShaped(<embers:stamper>, [[<moreplates:manasteel_plate>, <embers:mech_core>, <moreplates:manasteel_plate>],[<embers:plate_caminite>, <magneticraft:iron_hammer>, <embers:plate_caminite>], [null, null, null]]);
recipes.addShaped(<embers:cinder_plinth>, [[null, <minecraft:hopper>, null],[<extrautils2:trashcan>, <embers:mech_core>, <extrautils2:trashcan>], [<embers:block_caminite_brick>, <minecraft:furnace>, <embers:block_caminite_brick>]]);
recipes.addShaped(<embers:block_furnace>, [[<embers:plate_caminite>, <minecraft:hopper>, <embers:plate_caminite>],[<embers:plate_caminite>, <embers:mech_core>, <embers:plate_caminite>], [<embers:item_pipe>, <embers:block_caminite_brick>, <embers:item_pipe>]]);
recipes.addShaped(<embers:ember_activator>, [[null, <minecraft:hopper>, null],[null, <embers:mech_core>, null], [null, <minecraft:furnace>, null]]);
recipes.addShaped(<embers:mech_core>, [[<embers:block_caminite_brick>, <minecraft:glass>, <embers:block_caminite_brick>],[<minecraft:glass>, <botania:manaresource>, <minecraft:glass>], [<embers:block_caminite_brick>, <minecraft:glass>, <embers:block_caminite_brick>]]);
recipes.addShaped(<environmentaltech:structure_frame_2> * 2, [[<environmentaltech:erodium_crystal>, <environmentaltech:structure_frame_1>, <environmentaltech:erodium_crystal>],[<immersiveengineering:material:27>, <environmentaltech:erodium_crystal>, <immersiveengineering:material:27>], [<environmentaltech:erodium_crystal>, <environmentaltech:structure_frame_1>, <environmentaltech:erodium_crystal>]]);
recipes.addShaped(<calculator:powercube>, [[<refraction:reflective_alloy>, <calculator:reinforcedironingot>, <refraction:reflective_alloy>],[<calculator:reinforcedironingot>, <refraction:electric_laser>, <calculator:reinforcedironingot>], [<refraction:reflective_alloy>, <calculator:reinforcedironingot>, <refraction:reflective_alloy>]]);
recipes.addShaped(<refraction:lens> * 3, [[<refraction:reflective_alloy>, <refraction:reflective_alloy>, <refraction:reflective_alloy>],[<minecraft:glass>, <minecraft:glass>, <minecraft:glass>], [<refraction:reflective_alloy>, <refraction:reflective_alloy>, <refraction:reflective_alloy>]]);
recipes.addShaped(<refraction:magnifier>, [[<refraction:reflective_alloy>, <refraction:lens>, <refraction:reflective_alloy>],[<refraction:reflective_alloy>, null, <refraction:reflective_alloy>], [<refraction:reflective_alloy>, null, <refraction:reflective_alloy>]]);
recipes.addShaped(<refraction:assembly_table>, [[<refraction:reflective_alloy>, <refraction:lens>, <refraction:reflective_alloy>],[<refraction:reflective_alloy>, null, <refraction:reflective_alloy>], [<refraction:reflective_alloy>, <refraction:reflective_alloy>, <refraction:reflective_alloy>]]);
recipes.addShaped(<environmentaltech:solar_cont_2>, [[<environmentaltech:erodium>, <environmentaltech:solar_cell_erodium>, <environmentaltech:erodium>],[<environmentaltech:solar_cell_erodium>, <environmentaltech:solar_cont_1>, <environmentaltech:solar_cell_erodium>], [<environmentaltech:erodium>, <immersiveengineering:material:27>, <environmentaltech:erodium>]]);
recipes.addShaped(<environmentaltech:void_ore_miner_cont_2>, [[<environmentaltech:erodium>, <immersiveengineering:material:27>, <environmentaltech:erodium>],[<environmentaltech:erodium>, <environmentaltech:void_ore_miner_cont_1>, <environmentaltech:erodium>], [<environmentaltech:erodium>, <environmentaltech:laser_lens_crystal>, <environmentaltech:erodium>]]);
recipes.addShaped(<botania:cellblock> * 4, [[<minecraft:tallgrass:1>, <minecraft:tallgrass:1>, null],[<minecraft:tallgrass:1>, <minecraft:tallgrass:1>, null], [null, null, null]]);
recipes.addShaped(<botania:cellblock> * 16, [[<minecraft:potato>, <minecraft:beetroot>, null],[<minecraft:carrot>, <minecraft:cactus>, null], [null, null, null]]);
recipes.addShaped(<refraction:reflective_alloy> * 2, [[<lightningcraft:ingot>, <lightningcraft:ingot:1>, <lightningcraft:ingot:2>],[null, null, null], [null, null, null]]);
recipes.addShaped(<environmentaltech:litherite_crystal> * 4, [[<planttech2:kanekium_nugget>, <psi:material:2>, <planttech2:dancium_nugget>],[<psi:material:2>, <planttech2:plantium_ingot>, <psi:material:2>], [<planttech2:kinnoium_nugget>, <psi:material:2>, <planttech2:lenthurium_nugget>]]);
recipes.addShaped(<psi:programmer>, [[<minecraft:iron_ingot>, <psi:psi_decorative>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <forestry:chipsets:3>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, null, <minecraft:iron_ingot>]]);
recipes.addShaped(<psi:cad_assembler>, [[<minecraft:iron_ingot>, <minecraft:piston>, <minecraft:iron_ingot>],[<minecraft:iron_ingot>, <forestry:chipsets:3>, <minecraft:iron_ingot>], [null, <minecraft:iron_ingot>, null]]);
recipes.addShaped(<psi:cad_assembly>, [[null, null, null],[<minecraft:iron_ingot>, <minecraft:iron_ingot>, <minecraft:iron_ingot>], [<minecraft:iron_ingot>, <forestry:crafting_material:1>, null]]);
recipes.addShaped(<buildcraftsilicon:assembly_table>, [[null, null, null],[<magneticraft:heavy_plates:5>, <magneticraft:tesla_tower>, <magneticraft:heavy_plates:5>], [<magneticraft:heavy_plates:5>, <forestry:hardened_machine>, <magneticraft:heavy_plates:5>]]);
recipes.addShaped(<planttech2:plantium_ingot> * 4, [[<minecraft:wheat_seeds>, <ore:ingotBronze>, <minecraft:wheat_seeds>],[<ore:ingotBronze>, <minecraft:wheat_seeds>, <ore:ingotBronze>], [<minecraft:wheat_seeds>, <ore:ingotBronze>, <minecraft:wheat_seeds>]]);
recipes.addShaped(<magneticraft:crushing_table>, [[<minecraft:stone_slab>, <minecraft:stone_slab>, <minecraft:stone_slab>],[null, <forestry:sturdy_machine>, null], [<minecraft:planks>, <minecraft:planks>, <minecraft:planks>]]);
recipes.addShaped(<forestry:sturdy_machine>, [[<ore:ingotBronze>, <ore:ingotBronze>, <ore:ingotBronze>],[<ore:ingotBronze>, <botania:blazeblock>, <ore:ingotBronze>], [<ore:ingotBronze>, <ore:ingotBronze>, <ore:ingotBronze>]]);
recipes.addShaped(<minecraft:cake>, [[<minecraft:milk_bucket>, <minecraft:milk_bucket>, <minecraft:milk_bucket>],[<minecraft:sugar>, <minecraft:egg>, <minecraft:sugar>], [<minecraft:baked_potato>, <minecraft:baked_potato>, <minecraft:baked_potato>]]);
recipes.addShaped(<efab:base>, [[null, <minecraft:gold_ingot>, null],[<minecraft:gold_ingot>, <minecraft:diamond>, <minecraft:gold_ingot>], [null, <minecraft:gold_ingot>, null]]);
recipes.addShaped(<efab:grid>, [[<minecraft:gold_ingot>, <immersiveengineering:metal>, <minecraft:gold_ingot>],[<immersiveengineering:metal>, <avaritia:compressed_crafting_table>, <immersiveengineering:metal>], [<minecraft:gold_ingot>, <immersiveengineering:metal>, <minecraft:gold_ingot>]]);
recipes.addShaped(<botania:altar>, [[<minecraft:stone_slab>, <botania:petalblock:8>, <minecraft:stone_slab>],[null, <minecraft:stone>, null], [<minecraft:stone>, <minecraft:stone>, <minecraft:stone>]]);
recipes.addShaped(<minecraft:hay_block>, [[<minecraft:tallgrass:1>, <minecraft:tallgrass:1>, <minecraft:tallgrass:1>],[<minecraft:tallgrass:1>, <minecraft:tallgrass:1>, <minecraft:tallgrass:1>], [<minecraft:tallgrass:1>, <minecraft:tallgrass:1>, <minecraft:tallgrass:1>]]);
recipes.addShaped(<contenttweaker:jiban_moju> * 4, [[null, <ore:ingotSteel>, null],[<ore:ingotSteel>, null, <ore:ingotSteel>], [null, <ore:ingotSteel>, null]]);
//File End
